### ISSUE TITLE
Create empty collections 

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#100]
Hi @vsoch,

as we talk in other thread, I would like to be able to create empty collections.

In my use case `USER_COLLECTIONS=False`, I need to create collections and to assign them to a new owner, an authenticated user without admin or superuser roles.

In my mind, admins will do this from the web UI, something like a new section/button in `my collections` to create new collections would be great. What do you think?

**Comment by victorsndvg** [comment]
Yuhuuuu! issue number #100 :)

**Comment by victorsndvg** [comment]
My robot say four!

**Comment by vsoch** [comment]
It's your lucky day @victorsndvg ! You should get a prize for #100 too! I've just added this ability to the current PR. The one thing you will need to do as an extra step is (still) the same procecure to assign an additional (or different) owner / contributor after. What I can't do is give any user (anyone that can create an empty collection) an ability to just auto-discover all other user names. Bad practice.

**Comment by victorsndvg** [comment]
Closing as it is being solved in #97 and related with #89
