### ISSUE TITLE
Assign multiple tags to a single image or rename tag

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#101]
Hi @vsoch,

I have a new request. I would like to have several tags for the same image. Think in something like the common `latest` tag.

Some possible use cases are:
  - the last published version of my software is 1.0.0. There is a new release 1.1.0. The API has not changed. I want my users not to be necessarily aware of this change and I provide a common tag (`version_1`) to access all version 1.X.X of my software. 
  - I'm creating my images in a CI process. The image is created and then tested. Sregistry stores the temporal image. The image is pulled and tested. If fails the image is removed. If succeeds the tag is renamed or a new tag is added to the image.

In my opinion, having a tag acting as symlink and pointing to a particular image, or even being able to rename a tage could increase the flexibility of the workflows while working with sregistry.

What do you think?

**Comment by victorsndvg** [comment]
My robot say five! :)

**Comment by vsoch** [comment]
What is this robot you are talking about? Haha. 

You can already do this, just push with the `--tag` variable to specify a different one. The common tag is like `collection/container:tag`

**Comment by victorsndvg** [comment]
101 ... you know ... My robot is funny, but not me :disappointed:  jaja

But if I do:
```
$ sregistry push --name collection/container --tag tmp image.simg
$ sregistry push --name collection/container --tag latest image.simg
```
What I'm doing is to store the same image twice in the server side, right?

If I'm wrong don't continue reading :)

I would like to do something like:
```
$ sregistry push --name collection/container --tag tmp image.simg
$ sregistry tag collection/container:tmp --newtag production
$ sregistry link collection/container:production --newtag latest
```

Tag renaming can have bad collateral effects ... as something that was there ... now is not there!!
But symlink-tags can be very useful. e.g During development stage you use `latest` tag and you evolve together with it, but in production mode you fix a `non-symlink-tag` to your service

**Comment by vsoch** [comment]
Yes you would be saving the same image in the server, but with different tags. If you were to push "tag" with "tmp" again it would be replaced, unless the container is frozen, in which case it would push a second image (with different version) and the same name tag.  What you are wanting to do is rename the local image first, and then push .  Try looking at sregistry rename (the client) and open issue there... working locally with images is outside the scope of the sregistry *server*

**Comment by victorsndvg** [comment]
> Yes you would be saving the same image in the server, but with different tags. 
This is what I would like to solve. Singularity images are heavy enought (hundreds of MBs or GB) to try to avoid duplicated storages, or at least give an alternative to do it.

Again, If I pubilsh a new release 1.1.0 and I want to publish the image as:
container/collection/1.1.0

If you were to push "tag" with "tmp" again it would be replaced, unless the container is frozen, in which case it would push a second image (with different version) and the same name tag. What you are wanting to do is rename the local image first, and then push . Try looking at sregistry rename (the client) and open issue there... working locally with images is outside the scope of the sregistry server

**Comment by vsoch** [comment]
The idea of being able to freeze is to prevent from replacing a particular tag. If you want to replace it you need to unfreeze it. If you have "rolling changes" that are "the same tag" then you would need to unfreeze, and then push to replace the file (it's not stored twice).

**Comment by victorsndvg** [comment]
It doesn't solve my expectations. If I want to publish the same image through SRegistry with 2 different tags:
```
$ sregistry push --name collection/container --tag tag1 image.simg
$ sregistry push --name collection/container --tag tag2 image.simg
```

I will have this in SRegistry:
```
collection/container:tag1
collection/container:tag2
```

Storing exactly the same image more than 1 times is undesirable from the point of view of the storage. I think we should avoid or, at least, provide an alternative to avoid duplicated images in the server side

Have you planned to deal with this?

If not feel free to close this thread

**Comment by vsoch** [comment]
If you don't want to store tag1 and tag2, then you would delete one. If you want to replace tag1 with an update, you can push again when it's not frozen. We cannot make the assumption, given that these decisions about what to store / not to store are up to the user, that it is always desired to delete. It's not the responsibility of sregistry to take any bias one way or the other, or make decisions for the user about how to use (or not use) the storage.

**Comment by victorsndvg** [comment]
This is why I would like to provide to users the option of creating symlink-tags.

Close the issue for not bother you more about this
