### ISSUE TITLE
Please add Active Directory Support

### ISSUE THREAD

**Issue by Trophime** [singularityhub/sregistry#102]
Hi,
could you please add support for active directory auth?
see https://github.com/susundberg/django-auth-ldap-ad

Thanks
Best
C

**Comment by vsoch** [comment]
Definitely can do! @dctrud can you give guidance here on integration with your current plugin (or is it different?)

**Comment by dctrud** [comment]
If you have an AD setup that supports TLS connections and password auth you should be able to do it from the current plugin, by setting the config appropriately.

Some notes are here: http://www.spannerbracket.com/wordpress/?p=40

Note you have to set options for referrals etc. for it to work with an AD LDAP server.

 The linked repo is needed for AD using SASL auth. I'm afraid I no longer have access to any AD server, so I'm not able to test / work up anything for this.

**Comment by vsoch** [comment]
Thanks @dctrud ! @Trophime I don't have this setup either (and i know nothing about LDAP mostly) but it sounds like this can be done with the current registry setup with a different config. If you want to read through the link shared by @dctrud we can possibly figure out the steps, then I'll offer to package our discussion here into some wisdom to put into the docs?

**Comment by sgabenov** [comment]
I think that in would be better, if you docker image vanessa/sregistry would come with included auth plugins. This will not affect any other plugins and it would not increase image size a lot. What do you think about it?

**Comment by vsoch** [comment]
Singularity Registry has LDAP plugins, and it's not wanted by everyone so the user has instructions for how to build in container. 

https://singularityhub.github.io/sregistry/docs/plugins/ldap

Closing issue.
