### ISSUE TITLE
wrong github repositories in docs

### ISSUE THREAD

**Issue by Trophime** [singularityhub/sregistry#103]
Hi, 
in the docs there are references to wrong github repositories:
```https://github.com/singularityware/sregistry-cli```.

Replacing `singularityware` by `singularityhub` fix the pbs, I guess

Best
C

**Comment by vsoch** [comment]
oh thank you for finding this! I did a grep and was only able to find one instance, under the client page here --> https://github.com/singularityhub/sregistry/pull/104 Did you find any others that I missed? If that looks good, I will merge!

**Comment by vsoch** [comment]
thanks! Please ping with another issue if there are any missed links, hopefully my grep got them all!
