### ISSUE TITLE
support for IDM keystore?

### ISSUE THREAD

**Issue by Trophime** [singularityhub/sregistry#105]
Hi,
Would it be possible to have also support for [IDM keystore](https://catalogue.fiware.org/enablers/identity-management-k)?
If it is already possible to use it I would be grateful to the person giving me
some hints how to set it up.

**Comment by vsoch** [comment]
there are a lot of links on that page and my control+F doesn't find keystore! Which one are you referring to? I'm not experienced with fiware, @victorsndvg can you comment? Are you using this?

**Comment by Trophime** [comment]
sorry got the wrong link
here is the good one: 
https://catalogue.fiware.org/enablers/identity-management-keyrock

**Comment by victorsndvg** [comment]
There is an open PR about this. I will try to update it as a pluggin and not as the backend, as @vsoch suggested.

@Trophime, as you already know, the MSO4SC repository will be updated next week. You can use it when it's ready. I will send an email

**Comment by vsoch** [comment]
ah fantastic! @victorsndvg when you get a skeleton down if you need help with the details tag me in!

**Comment by victorsndvg** [comment]
Close in favor of #31

**Comment by vsoch** [comment]
Integration with Singularity keys has been added (so you can push from the Singularity software) which is a standard, so I hope this meets the need!
