### ISSUE TITLE
rename repo / docs to sregistry-server

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#111]
Good idea @remyd1!

**Comment by vsoch** [comment]
hey @remyd1 I made subtle changes in the docs and main README so the reader is immediately hit with "This is a server." I am hesitant to rename the repo itself given Github pages links and the name of the container, but I think this change is sufficient to help clear up some (bad naming) choices by me. If it continues to be weird and confusing we can put on stage 2 thinking caps, haha.

**Comment by remyd1** [comment]
Maybe you can add something like :
"This software is part of the singularityhub project https://singularityhub.github.io
It can be used jointly with sregistry-cli and the singularity-hub registry."

Furthermore, this kind of intro would be useful for each sub-project.

Kind regards,
Rémy

**Comment by vsoch** [comment]
I'm working more on the page now, I'll link it here when I push.

**Comment by vsoch** [comment]
hey @remyd1 give this a look https://singularityhub.github.io/

**Comment by remyd1** [comment]
Hi @vsoch 

I have some display issues on your website using my smartphone (responsive web design ? ;) )

Concerning the name "Global Client" I suggest you to rename it into something like "Singularity Registry Client". Then, IMHO "Global CLient" would refer more to something like "Singularity Registry Client" + "Builders" + "Singularity Python".

Usually the README.md  file in the github repository is the entrypoint to many projects. You should refer to this page in each project.

 However this page (except display on mobile devices and maybe your naming policy ;) ) is perfect.

Kind regards
Rémy
