### ISSUE TITLE
SAML provider

### ISSUE THREAD

**Issue by jbd** [singularityhub/sregistry#121]
Hello,

The install documentation mentions the existence of a SAML provider. I'm using [Shibboleth](https://www.shibboleth.net/) I would be very interested to test it. 

Jean-Baptiste

**Comment by vsoch** [comment]
I can definitely add this! Consider it on the queue for after Globus is merged.

**Comment by vsoch** [comment]
hey @jbd just a heads up that this is mostly done --> https://github.com/singularityhub/sregistry/pull/127 I'll do some brief testing on my end but (after that) will need your help to review proper with an actual SAML xml credential.
