### ISSUE TITLE
Per-user quotas for container images?

### ISSUE THREAD

**Issue by fearful-symmetry** [singularityhub/sregistry#122]
This is an issue that came up during our internal testing of sregistry.

It would be nice is we had a way of giving users a container image quota based on the image size.
The size is contained in the `metadata` field on postgres, so the data is there.

`shub=> select metadata from main_container;`

We're testing with some fairly large images (and ran into a few problems, some that have already been documented on different GH issues) and it would be nice to be able to limit users to a certain size in GB for total uploads.

I do python, but I know nothing about django, so I'm not really sure what's needed to support this or where it would go.

**Comment by vsoch** [comment]
hey @fearful-symmetry there are now limits on the number of containers per collection, and rate limits for all views. Are you still wanting a limit on the total size (for a user across all collections, or per container?) I haven't had any issues with this on Singularity Hub, but I'd be interested to hear about what issues you ran into. I have found that just limiting the number of containers per collection, or collections per user, places a nice upper limit.

**Comment by vsoch** [comment]
Closing issue, no response.
