### ISSUE TITLE
Make owner button broken

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#130]
Hi @vsoch ,

I was trying to add new owners to a team but it does not work.

I think there is bug here (is not callink `make_owner` button):
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/templates/teams/team_details.html#L220

If I replace `add_owner` by `make_owner` it adds an user to the list of owners as expected, but the on the server side I get the following error:
```
uwsgi_1   | Traceback (most recent call last):
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
uwsgi_1   |     response = get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
uwsgi_1   |     response = self._get_response(request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
uwsgi_1   |     response = self.process_exception_by_middleware(e, request)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
uwsgi_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1   |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
uwsgi_1   |     return view_func(request, *args, **kwargs)
uwsgi_1   |   File "./shub/apps/users/views/teams.py", line 303, in add_owner
uwsgi_1   |     return JsonResponse({"message":message})
uwsgi_1   | NameError: name 'JsonResponse' is not defined
```

**Comment by vsoch** [comment]
Ruhroh, looks like a bug! Give this PR a try :)

https://github.com/singularityhub/sregistry/pull/131

**Comment by victorsndvg** [comment]
Sorry @vsoch !!

I forgot to mention some other bugs adding and removing owners:

- `messages.info` needs a request as the 1st argument:
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/views/teams.py#L224
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/views/teams.py#L240
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/views/teams.py#L243

- I don't know if this still failing If this the previous one is fixed, but `message` variable is not defined in some contexts here:
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/views/teams.py#L265
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/views/teams.py#L285
https://github.com/singularityhub/sregistry/blob/master/shub/apps/users/views/teams.py#L306

Hope it helps!

**Comment by vsoch** [comment]
hey @victorsndvg ! Just for fun, I'm trying out Gitlab too :)

https://gitlab.com/singularityhub/sregistry/merge_requests/132

And Microsoft acquisition might have something to do with that too :P

**Comment by vsoch** [comment]
haha I think GitLab servers are overwhelmed with traffic from users wanting to switch - let's do this one instead for now!

https://github.com/singularityhub/sregistry/pull/132
