### ISSUE TITLE
Production nginx configuration

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#133]
Hi @vsoch ,

although we improved our nginx configuration since #82, we still have some issues with big (3.5Gb) images and  simultaneous downloads.

I'm pretty sure that you have solved some of this problems in sregistry-hub. right?
Please, @vsoch , can you provide a production nginx configuration for sRegistry ?

really appreciated!

**Comment by vsoch** [comment]
I'm closing this because it's a repeat of https://github.com/singularityhub/sregistry/issues/109
