### ISSUE TITLE
Running sregistry from Singularity

### ISSUE THREAD

**Issue by josbake** [singularityhub/sregistry#147]
I am working in an environment that does not support the use of Docker. Was curious if there was a way to run the usually docker-composed images in Singularity or does Singularity even offer a viable analog to Docker-Compose?

**Comment by vsoch** [comment]
heyo! I can now better answer this question, the answer is yes, see https://singularityhub.github.io/singularity-compose. It's still fairly challenging given the permissions needed (fakeroot works for some) but minimally it's a start! Take a look at the examples linked from there to get started.
