### ISSUE TITLE
Support simultaneous downloads

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#149]
HI @vsoch ,

I think i fixed this in the past ... 

How can I configure the service to support several simultaneous download??

**Comment by victorsndvg** [comment]
Restoring some files finally work. I think the most important is uwsgi. What do you think?

an example here:
```
[uwsgi]
master = true
processes = 4
threads = 4
socket = :3031
chdir = /code/
post-buffering = true
log-date = true
max-requests = 5000
http-timeout = 3600000
socket-timeout = 120
wsgi-file = shub/wsgi.py

ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
```

**Comment by victorsndvg** [comment]
this is the diff with the current status of uwsgi in the repo:

```
$ git diff uwsgi.ini
diff --git a/uwsgi.ini b/uwsgi.ini
index 92e1eab..6c61200 100644
--- a/uwsgi.ini
+++ b/uwsgi.ini
@@ -1,10 +1,16 @@
 [uwsgi]
 master = true
-processes = 1
-threads = 1
+processes = 4
+threads = 4
 socket = :3031
 chdir = /code/
 post-buffering = true
 log-date = true
 max-requests = 5000
+http-timeout = 3600000
+socket-timeout = 120
 wsgi-file = shub/wsgi.py
+
+ignore-sigpipe = true
+ignore-write-errors = true
+disable-write-exception = true
```
Not an expert, but I think the timeouts prevent SIGPIPE errors with big images and the number of processes and threads enables simultaneous downloads

**Comment by victorsndvg** [comment]
feel free to close :)

Only an extra-non-related question. Is there any place describing the environment variables affecting sregistry-cli?? (like SREGISTRY_STORAGE)

I found my self diving into issues to find it! :sweat_smile:

**Comment by victorsndvg** [comment]
PS: I'm simultaneous download (only) a 4GB image and 1GB image in a loop since 1h, and still working

**Comment by vsoch** [comment]
For the SREGISTRY_STORAGE, why did you need to change it? Given that it's Dockerized, the location shouldn't change unless you are mucking around with things.

**Comment by victorsndvg** [comment]
sorry @vsoch , I mixed several things.

1.- 1h downloading in loop (tens of 4GB downloads). It's perfect!
2.- I need to test more the new upload module, but seems to work fine too. If not, I will open new issues.
3.- the SREGISTRY_STORAGE thing is related with `sregistry-cli`. I asked it in the wrong place.

**Comment by vsoch** [comment]
ah now my greps are finding it :) Here is the place you would need to looK! https://singularityhub.github.io/sregistry-cli/developers

**Comment by victorsndvg** [comment]
thanks!
