### ISSUE TITLE
Typo on front page

### ISSUE THREAD

**Issue by hearnsj** [singularityhub/sregistry#15]
So sorry... I don't mean to nitpick. On the front page:
Let's get familiar with the Registry, see Introduction Let's get started.
This would read better as:

Let's get familiar with the Registry - so get started by looking at the Introduction

**Comment by vsoch** [comment]
Does it look better now?

![image](https://user-images.githubusercontent.com/814322/29739267-54de01ba-89ee-11e7-91f5-65aa392449bc.png)

**Comment by hearnsj** [comment]
That is perfect.

**Comment by hearnsj** [comment]
That is perfect.
