### ISSUE TITLE
[Client] json.JSONDecodeError does not exist on CentOS7 python 2.7.5

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#16]
Installed the vsoch/singularity-python development branch to use the sregistry client on CentOS 7 (uses python 2.7.5).

On running there is an import error for JSONDecodeError from json. This is beause json.JSONDecodeError wasn't added until later versions of the json package than are with python 2.7.5.

A workaround would be to use the fact that JSONDecodeError subclasses ValueError, which is what the old json returns (https://stackoverflow.com/a/35214768)

```diff
index d5a4a89..61ef45b 100644
--- a/singularity/hub/__init__.py
+++ b/singularity/hub/__init__.py
@@ -25,9 +25,7 @@ SOFTWARE.

 '''

-from simplejson import JSONDecodeError as SimpleJSONDecodeError
 from requests.exceptions import HTTPError
-from json import JSONDecodeError

 from singularity.logger import bot
 import requests
@@ -244,7 +242,7 @@ class ApiConnection(object):
                 try:
                     response =  response.json()

-                except (SimpleJSONDecodeError, JSONDecodeError):
+                except (ValueError):
                     bot.error("The server returned a malformed response.")
                     sys.exit(1)
```

**Comment by vsoch** [comment]
Are you running this on the host or in the provided container? I don't expect the singularity python software to work on all old hosts - it uses other libraries that are likely to not work. Is there any reason you installed directly vs. in the provided Singularity file to build a container?

**Comment by dctrud** [comment]
I'm running on the host. Would be great if it could be run on at least hosts with Python 2.7, as it's a little bit of an extra faff to work with it in a container (making sure local image location is mounted into container, need --priveleged if using nested inside docker etc.). However, if you intend to only support running the client from inside a Singularity container please close this.

NB - this is the only issue I have with compatibility on CentOS 7 - with this change there don't seem to be any other compatibility issues. Am sure on CentOS6 there would be, as that has Python 2.6.

**Comment by vsoch** [comment]
okay let me fix that then, one sec! I agree I like running on the host better too :)

**Comment by vsoch** [comment]
okay, just pushed!

**Comment by dctrud** [comment]
Confirm working on CentOS 7 host now 🥇
