### ISSUE TITLE
[feedback] Cloud Builders or Storage Providers (possibly linked with Github, etc.)

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#160]
Would users be interested in having builders that deploy to google cloud, or similar object storage? For example this might look like a direct push to a cloud storage (and then pull, for example, from object storage on Google Cloud or Amazon S3) OR commit to some versoined controlled repo, and then build and deploy from there (to mirror Singularity Hub). This would be implemented as plugins to allow for different customization for different users / institutions. Please comment here!

**Comment by michaelmoore10** [comment]
Hi Vanessa,

  Yes, that may be very useful for our needs.  We use a combination of Openstack Swift and Ceph Object for object storage internally.  Our cloud environment is currently in the design stages, but we are looking at Azure/Google Cloud/AWS for hosting, so a storage provider that uses S3 and/or Swift client, but configurable to use on premise object tiers as well as cloud would be great!

**Comment by vsoch** [comment]
Excellent! So if we start with Swift/Ceph (local storage) for both the registry server and client, is that the (current) biggest bang for the buck because you already have it deployed?

**Comment by vsoch** [comment]
Yes in this case sregistry server would just serve as a metadata and organizational node to the Swift/Ceph storage. For example, probably something like:

## sregistry push
 - Check for permissions, collections, the same way as is done now
 - If permission is good, if necessary, create the collection object in the registry
 - add the container to Ceph/Swift storage (whatever this looks like)
 - update sregistry with a new container object on success.

## sregistry pull
 - query singularity registry server for the container metadata, also check permissions
 - if found, return the address (how to get) container from swift/ceph.

What I can't do is enforce some change in permission for the object storage. For example, ifs sregistry has permission for a container to be used by some team, the query to pull can return 200 but if something changes in storage the final response will be denied. We will have to test this to see what works best (and I'm not sure how the permissions model works.)

For development, do you have suggestions for how I can access a dummy endpoint to test the various APIs" It seems a bit burdensome to set up. The fall back i programming a client blindly and then having you and your team test and give me detailed responses for the various calls. That also sounds messy, haha. If there is a cluster I can access, *or* if there is a dummy deployment that is easy to set up via Docker / similar, that might make sense.

**Comment by vsoch** [comment]
For your use of the sregistry-cli (command line tool) do you have users install it locally? Or load via a module? I think what we would want to do is have an environment variable that says "use this backend storage, but also update Singularity Registry Server with the metadata" so that the basic local configuration would be something like:

```
SREGISTRY_CLIENT=ceph
SREGISTRY_SERVER=yes
export SREGISTRY_CLIENT SREGISTRY_SERVER
```
and then evocation would continue as discussed above. Then if you use the client (but not the registry server) you would just leave out the `SREGISTRY_SERVER` variable. But it would be important to make sure, for your users, that the correct set is always exported, because for example if they don't export the SREGISTRY_SERVER and then push a container, it would go to your storage (but sregistry server wouldn't know about it). A similar thing is that we use modules for Singularity to make sure to export the `SINGULARITY_CACHEDIR` to be on scratch, otherwise homes get eaten up almost immediately :)

**Comment by michaelmoore10** [comment]
Re: sregistry-cli:
I have deployed a sregistry-cli Singularity container that we have told the developers to use to push images to sregistry. I did this to simplify the support of sregistry-cli in our CentOS 6 environment.  There were enough big dependencies that had to be added to CentOS 6 that it made sense to just use a container.  Plus, it reinforces the model we are pushing for, everything in containers whenever possible.

For environment variables - I am already setting system-wide variables for things like SINGULARITY_CACHEDIR in an /etc/profile.d script that is managed/deployed by puppet.  If I need to set values for sregistry-cli, I can add those there too.

How would Singularity itself deal with pulling from an object-backed sregistry?  Or would we have to change to the model of pull with sregistry-cli and then run singularity against the locally pulled image?

Re: Testing and development - Ceph/Swift support two different APIs to interact with object storage, S3 client and Swift client.  I would probably pick S3 just because it is pretty much available everywhere.  I wish I was able to give you access to our environment to test/develop the code, but security....  

What cloud provider do you work with primarily?  I can see if there are any single-node deployments of Ceph for testing...  

If you know what sort of operations you need to run against Ceph, I can try to track down the calls you would need to make and provide docs for that.

I am more than happy to do whatever I can to help out with development and testing.

**Comment by vsoch** [comment]
> I have deployed a sregistry-cli Singularity container that we have told the developers to use to push images to sregistry. I did this to simplify the support of sregistry-cli in our CentOS 6 environment. There were enough big dependencies that had to be added to CentOS 6 that it made sense to just use a container. Plus, it reinforces the model we are pushing for, everything in containers whenever possible.

This is a great practice! I was going to suggest similar - to build the client with the environment variables exported that are needed so your users don't need to think about it.

> How would Singularity itself deal with pulling from an object-backed sregistry? Or would we have to change to the model of pull with sregistry-cli and then run singularity against the locally pulled image?

Whether or not the Singularity (proper) client can pull from the registry depends on one thing - whether or not the object store can serve web objects. For example, a Google Storage bucket has each object associated with a URL. The way Singularity Hub is able to pull with shub:// is by giving Singularity direct link to an image to download. It's quick and efficient because Singularity Hub doesn't need to do any negotiating to provide the image, just pass along the call. For Singularity Registry Server (and this may be where you are seeing slowness) since we use a filesystem that the server can see we don't technically pass on the url to "some other server" we do this:

```python
    filename = container.get_download_name()
    filepath = container.image.get_abspath()

    f = open(filepath, 'rb')
    response = FileResponse(f, content_type='application/img')
    response['Content-Disposition'] = 'attachment; filename="%s"' %filename
    response['Content-Length'] = os.path.getsize(filepath)

    return response
```
That particular view is returned via serializers, but you can basically see the server is sending a [FileResponse](https://kite.com/python/docs/django.http.response.FileResponse) that streams a binary object in chunks. This would be a limitation that serving containers from the registry filesystem has that using some (by default scaled) cloud storage does not.

From the above you see the base requirement - that the endpoint provides a file or response that streams into a binary file. You are right that we run into an (equivalent) issue for some storage that the server needs to do extra handling before delivering to the user. This is something we should avoid, actually, because if sregistry server needs to do this, then you should just interact with the storage directly.

So let's break this into cases.

## Case 1: The Object Storage Delivers Files for Download
This is easy and great! Singularity Registry Server simply is a management interface for this, and the endpoint plugs into Singularity easily.

## Case 2:The Object Storage requires special handling
Meaning that I can't ultimately reveal some url to download - a server middleman is needed to do something first. In this case, we can still have Singularity Registry server work as a (shared) organizational endpoint, but the actual interactions for pushing, pulling, etc. the objects would happen via the client. The sregistry (not Singularity) client would need to serve as a middleman to handlethese special operations, and then deliver the image to Singularity. The worst case is that you would use sregistry-cli as a manager, and then Singularity to run the containers.

To move forward, I'd like to suggest the following. Whatever we do, we will need to have sregistry-cli be an endpoint to interact with Ceph/Swift. How that works with Singularity Registry I'll have a better sense when I dig into this work. I'd suggest that I start this development to push /pull just with the client (to the user's local storage) and then go from there. I believe Singularity Registry Client already has Amazon as an endpoint too in case that helps.

We primarily have Google Cloud over here, but we also have access to Amazon if needed. Let me know if there is a way to get a (node?) up and running, then I'll start work on sregistry-cli.

**Comment by vsoch** [comment]
I'm going to try this: https://hub.docker.com/r/ceph/daemon/
Apparently, it's "super dope" http://www.sebastien-han.fr/blog/2017/06/27/New-Ceph-container-demo-is-super-dope/

**Comment by vsoch** [comment]
Does that give me everything that I need, or would I still need to deploy something in the cloud (that it connects to?)

**Comment by michaelmoore10** [comment]
Yeah, I think so.  RGW is the Rados Gateway.  That is the Ceph Object access point and that docker container sets it up.  In my opinion, you should be good to go.

**Comment by vsoch** [comment]
Great! I'll see if I can get started on this later this afternoon - immersed in data structures at the moment and it's fabulous :wink:

**Comment by michaelmoore10** [comment]
Haha!  No problem.  I've got my head buried in a bunch of automation changes for some GPU driver updates...  Take your time.

**Comment by fenz** [comment]
Hi! I'm interested in this feature as well but mostly in interfacing with S3-like storage. I saw that so far it was implemented a Ceph client for sregistry-cli and I was wondering if it will be the same for S3.
For testing S3 I guess Minio (https://www.minio.io/) can be used (here an example on how it works with S3 buckets: https://docs.minio.io/docs/minio-select-api-quickstart-guide.html). It is basically using "boto3" python library and compatible with other S3 object storage provider (in my case I need to use NetApp StorageGRID: https://github.com/NetApp-StorageGRID/code-examples/blob/master/s3-python/examples.py). I'll be more than happy in helping testing it.

**Comment by vsoch** [comment]
Awesome! I would really appreciate the help to test out an integration, and AWS is a good start because it's  fairly commonly used. I think we have aws for sregistry-cli, but just for pull -> https://github.com/singularityhub/sregistry-cli/tree/master/sregistry/main/aws so let's proceed with the same plan as I had wanted to do for Ceph - let me know your feedback on this:

 - integrate aws fully into sregistry-cli (with push and pull, likely using boto3 instead)
 - then develop the backend for sregistry that uses the same aws storage

Thoughts?

**Comment by fenz** [comment]
I was suggesting Minio just because it will be simple to test (same concept as Ceph container used in the previous case, without the need of an aws account) but I guess the key is to use boto3 (that is anyway from aws) which can be used for other S3 solution like Minio, NetApp and Ceph as well (http://docs.ceph.com/docs/mimic/radosgw/s3/python/).
Regarding the steps to follow, It makes completely sense: first as client in sregistry-cli and then backend in sregistry to directly use the S3 object store. In principle, using some storage driver like RexRay (https://github.com/rexray/rexray), you can mount the object store as volume and write the images there, but having the sregistry directly interfacing with the object store APIs will be probably better in term of performance and can avoid adding other dependencies. This is why I think this solution is more interesting.

**Comment by fenz** [comment]
The first option.
Minio is an object storage server, you can start it as docker container (like you had for Ceph) and test it. From the website:
"Amazon S3 API is the de facto standard for object storage. Minio implements Amazon S3 v2/v4 API. Use Minio SDK, Minio Client, AWS SDK and AWS CLI to access Minio server."
So I thought it was maybe useful to have something like this to test the S3 object store client.
But anyway, the boto3 solution should be quite generic and work with Ceph as well. 
Actually it is maybe just a problem with the naming, the solution you developed for Ceph is using Swift APIs so it could be called "Swift client" because it seems Ceph supports also S3 APIs (http://docs.ceph.com/docs/mimic/radosgw/s3/) and could be accessed/used by an "S3 client"
Does it make sense or I get something wrong?

**Comment by vsoch** [comment]
oh no this is very logical! And I agree that ceph should likely be called swift, I'll add that to the PR I do for this too. No time frame on when I can get this started, I'm pretty busy atm but definitely will get something underway in the next week.

**Comment by vsoch** [comment]
Here is the rename PR if you would care to review! https://github.com/singularityhub/sregistry-cli/pull/167 I'm closing up shop for today, will look at minio and aws tomorrow or later in the week / weekend!

**Comment by fenz** [comment]
I checked the change, it seems the folder "ceph" is gone but the "swift" one has not been added (don't know if this was on purpose).
Anyway I did some test with Minio and boto3, here is a simple example:
1. Start the Minio Server (https://docs.minio.io/docs/minio-docker-quickstart-guide):
docker run -p 9000:9000 -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 minio/minio server /data
you will have an output like this: 
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000
2. Install the boto3 python library (I did in another container)
pip/conda install boto3
3.  Create a bucket from python (https://docs.minio.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html):
import boto3

s3 = boto3.resource('s3',
                    endpoint_url='http://172.17.0.2:9000',
                    aws_access_key_id='minio',
                    aws_secret_access_key='minio123')

s3.create_bucket(Bucket='test')

4. Create a file and upload into the bucket
# upload a file from local file system '/home/jovyan/testBucket.txt' to bucket 'test' with 'testBucket.txt' as the object name.
s3.Bucket('test').upload_file('/home/jovyan/testBucket.txt','testBucket.txt')

5. Check the file with the browser (http://172.17.0.2:9000)

Hope this helps.

**Comment by vsoch** [comment]
That's just a terrible error on my part- of course it won't work without the swift folder! I just added if you want to take a look.

Thanks for the example! I'll try to give it a look soon.

**Comment by vsoch** [comment]
okay I'm just going to start working on this, the original poster that wanted ceph/swift can test and report if he has issue.  What I'm going to do is extend the current aws client (which just does pulling) to use boto3 and then handle push too.

**Comment by vsoch** [comment]
Actually, this aws looks like it's for elastic container registry (different than s3!) I'll just call this endpoint s3 since most are familiar with that uri.

**Comment by fenz** [comment]
> Actually, this aws looks like it's for elastic container registry (different than s3!) I'll just call this endpoint s3 since most are familiar with that uri.

Exactly, this is what I got as well. I guess now you should decide if to use the "client" or the "resource" class from boto3 (https://stackoverflow.com/questions/42809096/difference-in-boto3-between-resource-client-and-session). But I don't think it will change much.

**Comment by vsoch** [comment]
The minio bird is adorable! 
![aws-minio2](https://user-images.githubusercontent.com/814322/50317221-78c8ce00-0488-11e9-8d05-422df20db07f.png)

He looks like a paperclip that was wrangled, but then found meaning and beauty in his new shape.

**Comment by fenz** [comment]
Just thought the link I shared before is not the best, here there's a better explanation: https://realpython.com/python-boto3-aws-s3/#client-versus-resource 
Let me know if you need any help from my side

**Comment by vsoch** [comment]
Thanks, this is great! I'm pooping out today but I got a good start, and this seems pretty reasonable to get implemented soon. I'll definitely take you up if I run into trouble!

**Comment by vsoch** [comment]
okay, ready for testing! https://github.com/singularityhub/sregistry-cli/pull/169 I'm done for today, so please take your time.

**Comment by vsoch** [comment]
Google Cloud Build was added linked with Github (and ceph / minio to sregistry client) so I'm going to close the issue.
