### ISSUE TITLE
Contributor member of a team can not see the containers

### ISSUE THREAD

**Issue by romainhild** [singularityhub/sregistry#161]
I'm a contributor of a team and on the list of collections, if I search for the corresponding collection I cannot see it.
The only way to see it, is to click on "Top Collections" and then on "Top Downloads", only then I can see the collection but when I click on it, I have a message "This collection is private."

Is there a way to see the list of containers of the team when we are only a contributor ?

**Comment by vsoch** [comment]
This is likely a bug. I’ll take a look and get back to you later today!

**Comment by vsoch** [comment]
@victorsndvg your feedback here! We originally had discussed that a contributor, meaning a member of a team added as a contributor to a collection, can pull containers if the collection is private. We didn't say this meant the contributor could have edit access to the collection. Could you comment on the issue here?

**Comment by vsoch** [comment]
My thinking:
 - team contributor added to a collection as contributor --> can pull and view
 - team contributor added to a collection as owner --> can edit collection

**Comment by vsoch** [comment]
hey @romainhild ! Here is a PR for you to test : https://github.com/singularityhub/sregistry/pull/162

I've added checks to see if the user is a contributor, and given contributor, you should be able to see it in the "all collections" and single collection views.

**Comment by prudhomm** [comment]
@vsoch just my two cents what is the contribution of a contributor if he/she only pulls or view.
I would say he/she is only a member with read-only access.
A contributor would be able to upload/push to the collection. read-write access
An owner has read-write access + administration privileges (add/remove member/contributor, change permisions...)

what do you think?

**Comment by vsoch** [comment]
I do agree the terms do not describe the permissions well! Let's wait to hear from @victorsndvg because we had a lot of conversation about this, and it maybe should be that the permissions maintained (with a different name) or the permissions updated to be more extensive.

**Comment by victorsndvg** [comment]
Hi @prudhomm and @vsoch ,

I agree with you. From my point of view this is only a naming convention issue. 

Which name is better to describe the `read-only` collection membership?

maybe `member`/`user`? or simply `read-only`?

I think that discussion on permissions update can be performed too, but it's a more large and complex discussion. I can think about other useful intermediate layers/permissions for `sregistry`, but I have to say that right now my needs are  satisfied with the current roles and permissions.

**Comment by romainhild** [comment]
@vsoch I would be glad to test the PR, but I don't know how to do it.
I'm only a user of the website.

**Comment by victorsndvg** [comment]
@vsoch , I tested it, it seems that there is a bug in the code that I already commented in the pull request.

FYI, I think is not working as expected. I check this behaviour update with a `contributor` role and I was able to see all the private collections (and contents), not only the one I'm contributor ...

**Comment by vsoch** [comment]
@victorsndvg I had changed it so that the "contributor" can view collections - should this go back to how it was ? (Also, the bug was fixed with collection --> instance).

**Comment by victorsndvg** [comment]
@vsoch , for me is not important to let a contributor to see anything in the webUI. In fact, I don't want them to use the webUI. In the workflow I'm thinking, only owners ( developers  or software providers) should need to take a look to the collection in the webUI.

Anyway, this could be useful for other stakeholders. From my point of view, for a generic contributor it has sense to be able to see the collections/containers he/she can pull.

 Maybe @romainhild or @prudhomm can provide more details on their needs

**Comment by vsoch** [comment]
Yes @romainhild and @prudhomm please comment on why you need the web UI to just pull. Thanks!

**Comment by romainhild** [comment]
For me it was to know the different names of the images, because I had other problems to pull.
I agree that if all goes well and we only want to pull an image which name we know, that is not needed.

But I guess that it is the same question of what a contributor do in the team. If I want to contribute to the images, I might need/want to know which one exist.
If I just want to use them, it might be unnecessary.

It is also weird for me that the message is "This collection is private" whereas I'm part of the team.

Anyway, keep in mind that I don't use sregistry very often and I might very well miss something important!

**Comment by vsoch** [comment]
@romainhild try:

```
$ SREGISTRY_CLIENT=registry sregistry search
[client|registry] [database|sqlite:////home/vanessa/.singularity/sregistry.db]
Collections
1  library/busybox:latest	http://127.0.0.1/containers/1
2  pancakes/busybox:latest	http://127.0.0.1/containers/2
3  lovey/busybox:latest	http://127.0.0.1/containers/3
```
And then let's talk about if the user with this permission should be able to view, or maintain as it is now (and not use web UI). I think given using on an HPC resource, we should be more conservative about explosing webby views (admins only) and optimize interaction from command line.

**Comment by romainhild** [comment]
Ah indeed, I was not aware that we could do the search from the command line. But it solves my problem.
For the rest, I think that I'm not the best person to talk about it, I'm not enough familiar with how sregistry works.

**Comment by vsoch** [comment]
@victorsndvg I just tweaked the PR to fix the bug, and changed the name of the Contributor to add more specific description that it is read only (command line access) when you get a chance to test!

**Comment by victorsndvg** [comment]
great @vsoch , I will test this later this week. Thanks!

**Comment by vsoch** [comment]
Awesome, thank you @victorsndvg !

**Comment by victorsndvg** [comment]
@vsoch , I've tested with the latest changes (#162)  and it seems it works perfect.

Thanks!
