### ISSUE TITLE
How to enable "Teams" setup?

### ISSUE THREAD

**Issue by Smahane** [singularityhub/sregistry#168]
Hello,

I'm going through the documentations to setup sregistry. I got the  server up and running.  I'm trying to create a "Team" but there is nothing in the UI. Anything im missing in the setup? Any help please?

![image](https://user-images.githubusercontent.com/5471356/48445249-f6dbdb80-e74a-11e8-9a64-106a56d2734e.png)

**Comment by vsoch** [comment]
It doesn’t look like you are logged in... try logging in first! Did you follow the complete instructions for adding an admin or manager too? It’s good practice to start from the beginning of the install instructions so you don’t run into these issues! Let me know how that goes and I’m glad to help further if needed.

**Comment by Smahane** [comment]
Thank you for your help. 
Yes I believe i went through everything and i couldn't get the login part to work. I was hoping i can move forward without it.
I have the USER_COLLECTIONS = True and the ENABLE_GITHUB_AUTH=True. I setup the  SECRET_KEY, and the SOCIAL_AUTH.. keys after i registered the application on github.  There is a problem with the callback url that i can't seem to explain. 

If im logged in with 127.0.0.1, it redirect back to localhost and I get:

![image](https://user-images.githubusercontent.com/5471356/48446078-2390f280-e74d-11e8-9262-66eaec603814.png)

And if im logged in with 'localhost', i get:
![image](https://user-images.githubusercontent.com/5471356/48446272-a914a280-e74d-11e8-961a-cd3b78f3f08a.png)


This is my github setup:
![image](https://user-images.githubusercontent.com/5471356/48446132-4e7b4680-e74d-11e8-9362-0b8abdaf6199.png)

**Comment by vsoch** [comment]
You are close! From the top screenshot I can see that the reason is a redirect uri mismatch. Rest assured that I have set these kind of things up a million times, and I run into this quite often. The providers are uite strict about theurl matching to a t. This means https vs http, and even leading slashes. I think you might be missing just that in the callback url - try something like this:

![image](https://user-images.githubusercontent.com/814322/48447944-77aacf80-e76b-11e8-9ed6-6530a30f22a0.png)


Another thing I run into is using browsers that enforce https, which is problematic when you are testing http. That would be the second bug. Sometimes it even logs me in (gives me an error page) but then I go backto 127.0.0.1 and I'm logged in!

Also, are you setting this up to test or just for yourself? Note thatif/when you deploy it for an actual server, you will want a domain name (and https) to replace this development / local testing setup.

**Comment by Smahane** [comment]
Unfortunately no luck! 
I'm setting this up for me to be able to share some containers internally with others.  Hoping that others can just do something like "sregistry pull $ipaddress:/<$containerName>"  to get a container

**Comment by Smahane** [comment]
I did exactly as you recommended with Firefox. I tried chrome but it doesn't have an option to setup the socks5 proxy setting. What browser did you have success with?

yes sregistry client is my back up plan if singularity registry doesn't work. The long time goal to eventually make for production.

**Comment by vsoch** [comment]
I can't test this right now because I have a few other things in the queue first, but I should be able to by sometime next week - I can share with you these details then.

**Comment by vsoch** [comment]
Login from chrome

![image](https://user-images.githubusercontent.com/814322/48518798-c1adb700-e838-11e8-89ef-f71b623a9ab8.png)

click Github

![image](https://user-images.githubusercontent.com/814322/48518817-cf633c80-e838-11e8-9af2-8ebc475621db.png)


I'm logged in :)

![image](https://user-images.githubusercontent.com/814322/48518902-0cc7ca00-e839-11e8-92a0-7bec66d880a7.png)

Please show me what you have in your secrets (and replace the values with XXX) and then the most recent of your configuration in Github (and include the sidebars so we see where you added it).

**Comment by Smahane** [comment]
That is the content of my shub/settings/secrets.py. just this page wouldn't let me upload it with the .py extension.

**Comment by vsoch** [comment]
ok, noted! What do you have under config.py in settings, this?

```
# DOMAIN NAMES

DOMAIN_NAME = "http://127.0.0.1"
DOMAIN_NAME_HTTP = "http://127.0.0.1"
DOMAIN_NAKED = DOMAIN_NAME_HTTP.replace('http://','')
```

**Comment by vsoch** [comment]
And your configuration is under (User Profile) --> Settings --> Developer Settings -> OAuth App?

**Comment by vsoch** [comment]
For my scope in secrets, I have

```
SOCIAL_AUTH_GITHUB_SCOPE = ["admin:repo_hook",
                            "repo:status",
                            "user:email",
                            "read:org",
                            "admin:org_hook",
                            "deployment_status"]
```
Actually, do you have DEBUG=True somewhere? That might help show the error in the console. I usually have this in secrets for development.

**Comment by Smahane** [comment]
I don't have SOCIAL_AUTH_GITHUB_SCOPE (though it's not needed?) or DEBUG=True setup. The Domain names are the same as yours.
I will play  with all of these variable and update you

**Comment by vsoch** [comment]
The error is clear, the redirect uri that you are giving Github doesn't match what the server is giving, so you need to make those two things clear. See https://developer.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/

You could also try registering a https address - it could be that your browser is starting with http and redirecting (ultimately)to http so it mismatches based on that

**Comment by vsoch** [comment]
I don't think it's needed, and per my note the me of the past didn't think so either :)

**Comment by vsoch** [comment]
The original issue was addressed, and the following discussion pertains to logging in with GitHub. Closing issue, as it was addressed to the best of my ability.
