### ISSUE TITLE
Unauthorized on sregistry push 

### ISSUE THREAD

**Issue by sunyi000** [singularityhub/sregistry#174]
**Describe the bug**
I can login to my local sregistryhub using github account. 

The token json string is stored in $HOME/.sregistry

SREGISTRY_CLIENT_SECRETS and SREGISTRY_CREDENTIALS are both set correctly

Then I did a sregistry push command from another machine. In the uwsgi docker log the error I got is 

DEBUG b'sunyi000' is not a valid user, request invalid.
Internal Server Error: /api/upload/chunked_upload
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "./shub/apps/api/actions/push.py", line 76, in collection_auth_check
    raise PermissionDenied(detail="Unauthorized")
rest_framework.exceptions.PermissionDenied: Unauthorized

I tried to print the exception in  validate_request function, the exception is

"User matching query does not exist."

but username variable has the correct value. 
No errors in nginx container

**To Reproduce**
1. login to local sregistryhub using github
2. copy token json string to $HOME/.sregistry
3. set environment variable SREGISTRY_CLIENT_SECRETS
4. sregistry push --name collection/test:latest test.img

Appreciate for any help on this
thanks

**Comment by vsoch** [comment]
You shouldn't need to set SREGISTRY_CLIENT_SECRETS if you are putting them in your home. Try unsetting that. The other question is, are you sure the directory / file detected as home (where you have the file) is what your client is using? For example, if you are running from a Docker container, home would be /root.

**Comment by vsoch** [comment]
To see what users your registry knows, shell into the container:

```
docker exec -it <container> bash
```
start a shell
```
python manage.py shell
```
Then look at the users.

```
from shub.apps.users.models import *
User.objects.all()
```

**Comment by sunyi000** [comment]
I have unset SREGISTRY_CREDENTIAL

for testing, I copied .sregistry file to /tmp. and set SREGISTRY_CLIENT_SECRETS to /tmp/.sregistry
same error..

I then shell into the container uswgi, started a shell. The output of the users are 
<QuerySet [<User: sunyi000>]>

so it seems I'm in the users objects.

**Comment by vsoch** [comment]
You shouldn't need to set any of those environment variables - it defaults to your home. Try unsetting them, verifying that the file is created, and then you need to (manually) add the username and token there. If you look at the interface when you are logged in there should be a token button with a json object to save.

**Comment by vsoch** [comment]
I don't know the details of the file, but it looks like it's reading it as bytes and not a string?

```
b'sunyi000' is not a valid user, request invalid.
```
E.g., `b'sunyi000` is different from `sunyi000`

You have good logic to figure this out - you have one server where it works, and one where it doesn't. Figure out how these two things are different. Modify the non working server, one step at a time, to be like the working one. I can't do this for you, I can only give advice / feedback on things you see and try.

**Comment by sunyi000** [comment]
1. unset the SREGISTRY_CLIENT_SECRETS
2. I'm very certain that the file is created with the correct token and username from the 
3. if you look at the code utils.py in this github, and try to print 'username'  variable. b'sunyi000' is what comes out after 
 username = base64.b64decode(username)
in utils.py
i have even tried 
 username = base64.b64decode(username).decode("UTF-8") 
to make it as string. but same thing.
4. I guess something happen in user = User.objects.get(username=username) but I could not find out the actually code in get because i'm not familay with django..

5. I dont have a working server anymore, after pulling the newsest code from the github.

6. I think the only thing I will do now is to revert to the working commit..

**Comment by vsoch** [comment]
You can try putting print statements in, for example:

```
print(username)
user = User.objects.get(username=username)
```
and then just restart the server:

```
docker-compose restart 
```

**Comment by vsoch** [comment]
ah hold the phone! I just reproduced your error. Give me a few minutes to work on it!

**Comment by sunyi000** [comment]
i did that many times. as I mentioned before 
1.username has the correct value sunyi000,if I added decode("UTF-8") to your base64 decode line
2. username is bytes which is b'sunyi00' if I don't put that line..

**Comment by vsoch** [comment]
hey I'm working on it, I can't offer more than that. Thank you for your patience.

**Comment by vsoch** [comment]
I fixed the issue, and it was exactly as I noted above, an issue with the username needing to be decoded. Please test.

**Comment by vsoch** [comment]
What is confusing is how you could report that it worked pushing from one server, but not another. The error I fixed above would consistently not work regardless of where you pushed from. Strange!

**Comment by sunyi000** [comment]
- I only have one server. it worked a few day ago, but stopped working after pulling the newest changes from github after the bitbucket changes.
- If you look at the other question I post it on https://github.com/singularityhub/circle-ci/issues/4 from the beginning you will understand what I did

**Comment by vsoch** [comment]
ah okay, so it's *not* the same registry interacted with from a different server, it wasn't working from any server. That was my misunderstanding. Does it work now?

**Comment by sunyi000** [comment]
yes it's working now. thank you

**Comment by vsoch** [comment]
Awesome! Thanks for your patience.
