### ISSUE TITLE
sregistry push -> invalid choice?

### ISSUE THREAD

**Issue by tamasgal** [singularityhub/sregistry#179]
Hi there, singularity is awesome and today I decided it's time to set up a private registry for our collaboration. It worked well (without any OAuth for now, to keep things simple).

So I though pushing to the registry should work out of the box. I installed the `sregistry-cli` but when I do `sregistry push ...`, I get an error saying that `push` is an invalid choice. What am I missing?

```
░ tgal@staticbox:~ py-3.7.2
░ 14:43:59 [I] ➜ sregistry push
usage: sregistry [-h] [--debug] [--quiet]
                 {version,backend,shell,images,inspect,get,add,mv,rename,rm,rmi,search,pull}
                 ...
sregistry: error: argument command: invalid choice: 'push' (choose from 'version', 'backend', 'shell', 'images', 'inspect', 'get', 'add', 'mv', 'rename', 'rm', 'rmi', 'search', 'pull')
```

**Comment by vsoch** [comment]
What client are you trying to use? The default (Singularity Hub) does not allow push. If you wanted Singularity Registry, for example, you'd need to do:

```bash
# one off example
SREGISTRY_CLIENT=registry singularity push...
```
more than one time...
```bash
export SREGISTRY_CLIENT=registry 
singularity push...
```

**Comment by tamasgal** [comment]
Oh, I was probably mixing up `sregistry` with `singularity`, sorry for that! I will try and close this...

**Comment by vsoch** [comment]
No worries! It’s unfortunatel confusing given all the potential clients. Hopefully I can figure how to make it better someday :)
