### ISSUE TITLE
Google Oauth repeatedly shows Google account selection screen.

### ISSUE THREAD

**Issue by tamasgal** [singularityhub/sregistry#180]
I am not sure if this is a bug or a misconfiguration.

**Describe the bug**

I set up Google Oauth and everything worked fine, two users could log in and upload images. When I tried to log in on another machine, with a Google account which was already authenticated, it didn't work. After selecting the Google account to log in, it redirects to the very same page with the account selection.

As said, login procedure the first time works, but not a second one.

**To Reproduce**

The only way to reproduce it is currently logging in on our server. The second login will not succeed: http://singularity.km3net.de

**Comment by tamasgal** [comment]
Btw. when I do `docker-compose down` and `docker-compose up -d` again, I am able to login again. However, I need to accept the terms of service again. After that, if I log out once, I cannot login back.

**Comment by tamasgal** [comment]
This is a weird day. I don't know what happened, but it suddenly works. For everyone...

**Comment by vsoch** [comment]
Interesting! This sounds like an issue of the browser not remembering the login? I'm glad you got it resolved. If you run into issues with the browser generally the things I try are:

 - look in the console for errors 
 - try a different browser
 - make sure ad blockers, etc. aren't getting in the way

You are correct about docker-compose down (if you are using the postgres image).

**Comment by tamasgal** [comment]
Yeah I really did. I think in the end it was one line which I forgot to comment out in the `secrets.py`, not sure if it is related:

```
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline',
    'approval_prompt': 'auto'
}
```
