### ISSUE TITLE
Packages needed by plugins not installed by default into the container

### ISSUE THREAD

**Issue by pmargara** [singularityhub/sregistry#189]
Currently python packages needed by plugins are not installed by default into vanessa/sregistry container, it's required to rebuild image container with a modified Dockerfile or runs commands to install them inside the container's image.
I think that would be better if docker image includes dependencies for plugins.

This will not increase image size a lot and allows to have all the plugins working and included out of the box. What do you think about it?

This could be easly done by changing:
```
################################################################################
# PLUGINS
# You are free to comment out those plugins that you don't want to use

# Install LDAP (uncomment if wanted)
# RUN pip install python3-ldap
# RUN pip install django-auth-ldap

# Install Globus (uncomment if wanted)
# RUN /bin/bash /code/scripts/globus/globus-install.sh

# Install SAML (uncomment if wanted)
# RUN pip install python3-saml
# RUN pip install social-auth-core[saml]

################################################################################
```
to:
```
################################################################################
# PLUGINS

# Install LDAP (comment if unwanted)
RUN pip install python3-ldap
RUN pip install django-auth-ldap

# Install Globus (comment if unwanted)
RUN /bin/bash /code/scripts/globus/globus-install.sh

# Install SAML (comment if unwanted)
RUN pip install python3-saml
RUN pip install social-auth-core[saml]

################################################################################
```
If you agree with me I could prepare a pull request to address this.

**Comment by vsoch** [comment]
Hey @pmargara - this is intentional. It’s likely the case that users want a subset or not any plugins. If you read the instructions,  there are specific steps to take in order to install each of the plug-ins, one of them being uncommenting those lines of the Dockerfile and then rebuilding the image.  If you want it to be quick, you can even use the Vanessa/sregistry image as base and then add the needed libraries.  Please take a look at the documentation and let me know if you have any questions.

**Comment by vsoch** [comment]
You can either uncomment in the current Dockerfile and build:

```bash
$ docker build -t vanessa/sregistry .
```

Or you can try to use the image as a base (here is a Dockerfile.plugins example)

```bash
FROM: vanessa/sregistry:32744d8a59

# Install LDAP (comment if unwanted)
RUN pip install python3-ldap
RUN pip install django-auth-ldap

# Install Globus (comment if unwanted)
RUN /bin/bash /code/scripts/globus/globus-install.sh

# Install SAML (comment if unwanted)
RUN pip install python3-saml
RUN pip install social-auth-core[saml]
```
```
$ docker build -f Dockerfile.plugins -t vanessa/sregistry .
```
Either should create your base image. If you name it something other than vanessa/sreigstry (recommended) you can push it to Docker Hub in case you need it again. If you change the name, also be sure to change the name in docker-compose.yml.

**Comment by pmargara** [comment]
Hi @vsoch, I've sregistry up and running in a test environment ;-). The documentation is quite clear but you should also consider that in many sites changes to official containers are not very welcome.
If you think that is better to have plugins without dependency installed ok, but I think that could be an issue for some users.
I've also configured LDAPS, also this require some changes to the Dockerfile and docker-compose.yml, if you are interested I could share my changes (or upgrade the documentation if you prefer, but for me is better the first option).

**Comment by vsoch** [comment]
hey @pmargara that's great news! To play devil's advocate, I know of docker-compose applications that don't even provide a base container - they might have a section to build directly from a folder, or just instruct the user to do so. I provide it as a convenience or base, but given the (very large number) of possible combinations for "I want this plugin, not that one" it's fairly reasonable to ask the user to customize the build.

You are also correct that the configurations for a lot of these plugins are totally cluster specific - especially LDAP. I'm not an expert, but every configuration I see looks  a little different. The most that I can do is provide the base, and then the user must customize. Yes, it requires changes to the docker-compose and Dockerfile, and I've clearly documented them to assist with this process.

LDAP is hard to configure (even for more experienced users than I!) so it would be great if you might contribute your example use case to the docs. The docs are in the [docs folder](https://github.com/singularityhub/sregistry/tree/master/docs) under pages, and then the pages folder, and then LDAP is under plugins. If you see anything else that could be improved, please go for it! Your contribution is greatly appreciated.

**Comment by vsoch** [comment]
@pmargara thank you again for this feedback, in order to support the many different installation use cases it's almost unavoidable to give the user the power to customize the container, and need to build it. We had good discussion here, and I'm closing the issue.
