### ISSUE TITLE
[Client] gzip compression with -9 takes too long

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#19]
sregistry client is using gzip with -9 (best) compression. Default for gzip is -6.

-9 is giving minimal improvement in compression over the default, and takes a lot longer. When building and pushing 100s/1000s of images in an automated manner this can become a big issue. E.g. creating Singularity versions of docker biocontainers, sregistry's gzip -9 is the slowest step of the process.

Example compression on image created from the Singularity `examples/centos` definition. Original image is 769M on disk. Compression with -9 takes >4x as long, saves <1M in final compressed image size:
 
```
# Default gzip compression
21:08 $ time gzip centos.img && ls -la centos.img.gz
real    0m27.862s
user    0m27.529s
sys     0m0.332s
-rwxr-xr-x. 1 dave dave 163302185 Aug 26 09:07 centos.img.gz

# Current sregistry (-9) compression
21:10 $ time gzip -9 centos.img && ls -la centos.img.gz
real    2m3.429s
user    2m3.060s
sys     0m0.368s
-rwxr-xr-x. 1 dave dave 162702257 Aug 26 09:07 centos.img.gz
```

**Comment by vsoch** [comment]
-9 was recommended by @gmkurtzer and is what Singularity Hub uses. I definitely agree that time is important -- @gmkurtzer what are your thoughts?

**Comment by vsoch** [comment]
okay, I changed default to 6. This might be something that different registries have preference to change, right now it's set at 6, but if @gmkurtzer says it's important we can default to 9, and then have a variable / setting go back to 6.

@dctrud I'm going to open an issue where we can keep "customization /settings" that we might want to add.

**Comment by vsoch** [comment]
I think we can close this, because squashfs!
