### ISSUE TITLE
Need LDAP plugin setup documentation 

### ISSUE THREAD

**Issue by asmi10** [singularityhub/sregistry#198]
I am trying to configure LDAP plugin in sregistry, but the URL's mentioned in docs are not available
https://singularityhub.github.io/sregistry/plugins/
Would you able to provide document here?

**Comment by vsoch** [comment]
You just need to remove the trailing slash:

https://singularityhub.github.io/sregistry/plugins

Where did you find this particular url? I can fix it if it's in the docs.

**Comment by vsoch** [comment]
Nevermind just found it! :) grep to the rescue!

**Comment by vsoch** [comment]
This will be closed with #200 and #172
