### ISSUE TITLE
[ SETTINGS ] what custom settings should the registry have?

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#21]
This is a shared issue to put custom settings that we might want to add:

- [ ] **Gzip Compression**

Right now, the client does compression at -6. However, if -9 is important for reproducibility, it should be default. However, it comes at the cost of speed - it's rather slow to do. I think if -6 is ok, we should default to that. However if there is question, we should let the user decide with the most reasonable default.

 - [ ] **Colors / Logo**

I'd like it to be easy for the registry to (further) customize itself, with an institution logo / accent color.

**Comment by dctrud** [comment]
Not a request for a setting, but as custom settings are implemented could there be support for having them in a `settings/local.py` that would override defaults in `settings/config.py`? Would be good to have local customisations only in a minimal file that is in not included in the repo by default and easily mounted into pre-built docker container.

**Comment by dctrud** [comment]
- [ ] **Only private**
Force all container collections into being private

**Comment by vsoch** [comment]
For sure! That is the intent behind the config.py - I would want major stuffs to be controllable by the user.

**Comment by vsoch** [comment]
hey @dctrud I just added a config value for `PRIVATE_ONLY` in settings/config.py. It makes all collections private by default, and not changeable in the web interface. You could only make one public via command line being a superuser, if the need is ever there.

**Comment by vsoch** [comment]
ok I think we are good on this issue - settings go into config.py. Closing!
