### ISSUE TITLE
Dockerfile with build-args 

### ISSUE THREAD

**Issue by serlophug** [singularityhub/sregistry#218]
I'm developing an Ansible role (https://github.com/grycap/ansible-role-singularity-registry) to install sregistry by using your docker-compose recipes and sregistry. I want to automate the plugin's installation, so I need to uncomment some parts of the Dockerfile. I think that a good solution for avoiding search with regexp in the Dockerfile is using build-args to execute the desired RUN statements

**Comment by vsoch** [comment]
@serlophug this is really great! Would you like to maintain the repository here, in the case that other singularity users want to use / find it? Or is there a better way?

**Comment by serlophug** [comment]
@vsoch I prefer to maintain the repository in our Github organization (https://github.com/grycap/) due to we have a lot of Ansible roles. I think that one possible solution could be to create a section in the _sregistry_ documentation that describes how to use and configure the Ansible role (available at https://galaxy.ansible.com/grycap/singularity_registry). What do you think about it?

**Comment by vsoch** [comment]
Yes that's a great idea! Do you have some bandwidth to do it? I'm not a heavy ansible user so I probably wouldn't be best. But I'm also happy to give it a shot (if you can give some guidance about use cases, and background about your group) and then you can review.

**Comment by serlophug** [comment]
Yes, I can do it :) I 

Regarding our GRyCAp, it is a research group of the Institute for Molecular Imaging Technologies at the Universitat Politècnica de València, in Spain. The group focuses on the application of the multiple facets of distributed computing (e.g. Cloud computing, High-Performance Computing, Grid computing, Serverless computing, etc.) to different scientific areas that include, but are not limited to biomedicine, medical imaging and structural buildings. More information about our tools is available in https://www.grycap.upv.es/index.php/products/.

**Comment by vsoch** [comment]
Wow, that's incredibly awesome! If you guys ever want help for something related to containers, please don't hesitate to ask!

**Comment by serlophug** [comment]
Thank you and, if you want help about any of our tools or Ansible, don't hesitate to ask too :)
