### ISSUE TITLE
container tag replacement

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#22]
hey @dctrud are the tags for your biocontainers (originally) containing slashes, and they are replaced with `-`? I think we would want to either replace with something else, or just ensure there is only one slash (two slashes look weird)

**Comment by dctrud** [comment]
The original tags are named like that with the 2 dashes - see: https://quay.io/repository/biocontainers/ariba?tab=tags

**Comment by vsoch** [comment]
yeah I saw that, so weird! Alrightly, I'm ok with this, hehe.
