### ISSUE TITLE
Question: How do i change the DOMAIN_NAME_ variable in main.py?

### ISSUE THREAD

**Issue by Smahane** [singularityhub/sregistry#222]
Question on: https://github.com/singularityhub/sregistry/tree/master/_docs/install/settings.md#registry-contact

Hello,
I see that i have to change the domain name in the main.py. How and where do i change that?

Thank you,

**Comment by vsoch** [comment]
This looks like a typo in the docs! You will find the domain name settings under the settings folder, config.py -> https://github.com/singularityhub/sregistry/blob/master/shub/settings/config.py#L34 

I'll update the docs promptly.

**Comment by vsoch** [comment]
okay the docs should be fixed with the correct file, and also the link that gets put above to take you to the correct page. Let me know if you have any other questions, and feel free to close the issue if not.

**Comment by Smahane** [comment]
Thanks for the prompt fix.
i did change the 127.0.0.1 to mydomain name in config.py bit it doesn't work for some reason. The 127.0.0.1 still works! I'm wondering if im missing anything!

**Comment by vsoch** [comment]
Do a grep for 127.0.0.1 and see if you missed one.

**Comment by vsoch** [comment]
```bash
$ grep -R "127.0.0.1"
auth.py:SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://127.0.0.1'
config.py:DOMAIN_NAME = "http://127.0.0.1"
config.py:DOMAIN_NAME_HTTP = "http://127.0.0.1"
```
And don't forget that any time you make changes to the code, you need to restart uwsgi and worker with docker-compse

```bash
$ docker-compose restart uwsgi worker
```

**Comment by vsoch** [comment]
I think we resolved the issue, closing here and please let me know if you need additional help.
