### ISSUE TITLE
Connect Sregistry Client from within a docker container to a Singularity Registry running on localhost

### ISSUE THREAD

**Issue by pianopwner** [singularityhub/sregistry#223]
I'm probably missing something obvious here, but I'm having trouble connecting from a sregistry client in a docker container to a Singularity Registry I have running on my host. I have been able to do this fine with a sregistry client on my host with push/pull working. 

From within the docker container: I have set my SREGISTRY_REGISTRY_BASE to my docker0 IP + the port the nginx server is running on. Username and token are also set.

When I try a sregistry pull command nothing happens and the connection times out. 
Is there some additional setup that is required here? When I run 'sregistry backend ls' only hub is listed and no 'registry'. 

Apologies if this is a trivial question, I'm doing this as part of a uni project and it's all pretty new to me

**Comment by vsoch** [comment]
hey @pianopwner ! If you are working from inside the Docker container and you expect to connect to the host, the docker sregistry client can't actually see your host unless whatever endpoint you are using is connected to it. You would want to try a docker-compose.yml configuration that has the two connected.

**Comment by vsoch** [comment]
What you can try is adding another entry for your client into the docker-compose.yml for sregistry, OR you can just shell into your sregistry image (with a volume mounted) and use the client installed in there. If you pull containers to the volume in the container, they should show up on the host. But be careful of permissions - running in docker == sudo.

I would overall recommend using sregistry natively, *or* trying a Singularity container with sregistry so the interaction is more seamless.

**Comment by pianopwner** [comment]
Thank you for your speedy reply! In the end I included my client container in the docker compose, linked it to the nginx container and set my SREGISTRY_REGISTRY_BASE=http://nginx (name of linked nginx container). This resulted in my desired functionality.

**Comment by vsoch** [comment]
Great! I'm glad that it worked out for you. I'm going to close the issue, please re-open (or a new issue) if anything else comes up.
