### ISSUE TITLE
Singularity pull always pulls the same image, despite the name requested

### ISSUE THREAD

**Issue by olsonanl** [singularityhub/sregistry#227]
**Describe the bug**

I have a sregistry configured on a centos7 host using your Docker containers (I have a separate nginx build so I can push large containers but I have seen this behavior with thdocker container as well). I have also mounted the postgres data directory from the host to the postgres container so that the configuration is retained across restarts (it didn't seem to do that otherwise - perhaps I was doing something wrong?)

The problem is that I can push two separate images using sregstry-cli:

```
olson@spruce:~$ sregistry push --name p3-runtime sing/images/p3-runtime.sif 
WARNING Singularity is not installed, function might be limited.
[client|registry] [database|sqlite:////homes/olson/.singularity/sregistry.db]

[1. Collection return status 200 OK]
[================================] 6610/6610 MB - 00:00:00

olson@spruce:~$ sregistry push --name base-os sing/images/base-os.sif 
WARNING Singularity is not installed, function might be limited.
[client|registry] [database|sqlite:////homes/olson/.singularity/sregistry.db]

[1. Collection return status 200 OK]
[================================] 242/242 MB - 00:00:00
[Return status 200 Upload Complete]
```

I see the images in the web gui:

![image](https://user-images.githubusercontent.com/2152226/63891991-22634600-c9ac-11e9-906d-3f3e2e47ea14.png)

and when I download from the web I get what I expect:

```
-rw-r--r--@   1 olson  staff       6932062208 Aug 28 15:50 library-p3-runtime_latest.sif
-rw-r--r--@   1 olson  staff        253927424 Aug 28 15:54 library-base-os_latest.sif
```

However, if I use singularity to pull images, I get the same image when I use either name:

```
bash-4.2$ singularity version
3.0.2
bash-4.2$ singularity pull --library http://140.221.84.100 library/base-os
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Download filename not provided. Downloading to: base-os_latest.sif
 242.16 MiB / 242.16 MiB [=================================================================] 100.00% 82.39 MiB/s 2s
bash-4.2$ singularity pull --library http://140.221.84.100 library/p3-runtime
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Download filename not provided. Downloading to: p3-runtime_latest.sif
 242.16 MiB / 242.16 MiB [=================================================================] 100.00% 87.03 MiB/s 2s
bash-4.2$ ls -l
total 496000
-rwxrwx---+ 1 olson seed-users 253927424 Aug 28 15:47 base-os_latest.sif
-rwxrwx---+ 1 olson seed-users 253927424 Aug 28 15:48 p3-runtime_latest.sif
```

**To Reproduce**

See above.

**Expected behavior**

I expected to get the 6GB image when I pulled p3-runtime.

Thank you for any help!

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
What image is it pulling? It doesn't seem logical that, given a random uri (that doesn't exist) it would just pull some random image. Singularity Registry server certainly isn't set up for that, so we'd need to go backwards and maybe start with the image being pulled. If you are able to debug singularity and look at it's api request, and then go to that endpoint to see the container, that's even better.

**Comment by olsonanl** [comment]
Forbidden:

```
bash-4.2$ singularity  pull --nohttps shub://140.221.84.100/library/base-os
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: 403 Forbidden
```

I have a different (3.3.0) build of singularity I built from source for which I'm seeing the same behavior that we can debug with.

**Comment by olsonanl** [comment]
It's pulling one of the two images that is in place; I tried deleting and readding to see if it was the first in the list but it didn't change the behavior so I'm not sure why it's choosing that one.

**Comment by olsonanl** [comment]
Here is the uwsgi bit of logs when I pulled the nonexistent name:

```
[pid: 46|app: 0|req: 18/58] 140.221.70.11 () {30 vars in 438 bytes} [Wed Aug 28 16:17:37 2019] GET /v1/imagefile/library/alpabcdef:latest => generated 0 bytes in 11 msecs (HTTP/1.1 302) 6 headers in 251 bytes (1 switches on core 0)
[pid: 37|app: 0|req: 14/59] 140.221.70.11 () {32 vars in 555 bytes} [Wed Aug 28 16:17:37 2019] GET /containers/2/download/711f21f9-1835-4a2b-8a90-4d6863a6556b => generated 91697152 bytes in 231 msecs via sendfile() (HTTP/1.1 200) 4 headers in 173 bytes (288 switches on core 2)
```

**Comment by vsoch** [comment]
The uwsgi log unfortunately doesn't give us the API endpoint that Singularity is actually hitting - it's only targeting the library collection.

The typical use case isn't to have one library collection with differently named containers under it, but rather to have collections be ONLY for one namespace, like `library/ubuntu` and then variance in tags. The weird behavior you are seeing is because you are pushing containers that should be in different collections to the same one. The only hack to get around this would be to give them different tags, and then explicitly to ask for the tag. You generally don't want to do a push of an incomplete uri like that.

**Comment by olsonanl** [comment]
Per strace here is the request being made when using --library:

```
GET /v1/images/library/alpabcdef:latest HTTP/1.1
Host: 140.221.84.100
User-Agent: Go-http-client/1.1
Authorization: BEARER long-token-string
Accept-Encoding: gzip```
```

**Comment by olsonanl** [comment]
Aha. I hadn't made the new collection public; I thought they defaulted to public.

When I did that things began working properly with the shub url.

(So this seems doubly a bug with the --library entrypoint, since it was returning non-public data. Happy to help you debug there if need be)

**Comment by vsoch** [comment]
Haha, look at this comment :) https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/images.py#L64

It should be an easy fix actually! I'll do a quick PR for you to test. The library endpoint is based off of the sylabs library endpoint, but it's missing all of their authentication methods because they haven't made the spec public (and I can only guess so much). I probably forgot to do standard checks there for a private container - I can minimally do that!

**Comment by olsonanl** [comment]
Heh :-). Now that I've got the public/private thing figured I can continue with what I'm doing - wrapping up all the code and data for our analyses ... current image size is around 19GB with reference data included, and boots up amazingly quickly. Cool stuff.

**Comment by vsoch** [comment]
:scream: !

Here is a PR for the issue with private containers and the library endpoint - thanks for catching it! https://github.com/singularityhub/sregistry/pull/228

**Comment by vsoch** [comment]
I think we resolved this issue - closing. Thanks for the issue @olsonanl and good luck with your hefty containers! :muscle:
