### ISSUE TITLE
The admin/superuser is not able to remove a collection owned by a regular user

### ISSUE THREAD

**Issue by RonaldEnsing** [singularityhub/sregistry#229]
I've deployed an sregistry instance and created two users.
1) The first user has been created by logging in the sregistry instance using the github authentication. After the user has been created, I've set the permissions for this user to admin and superuser using `manage.py add_admin` and `manage.py add_superuser`. On the Django administration site I can see that everything looks good.
2) The second user I created from the Django administration site. It's not an account to be used by a real user, there is no github account associated. This account is used by a Continuous Integration pipeline. Only the access token will be used to push singularity images to the sregistry instance.

A collection is automatically created when an image is pushed from the CI/CD pipeline. However, I noticed that the superuser/admin is not able to remove/modify a collection owned by this user.

Is this the intended behaviour, or is this a bug? Possibly related: Would you suggest this setup when there is a need for pushing images from a CI/CD pipeline that is not associated with a real user?

How would you suggest to modify (and remove) a collection, maybe from a shell in the docker instance running sregistry?

**Comment by vsoch** [comment]
I don't (officially) support the Django administration site, and actually I think it would be best to remove those views because of that. So - I can't guarantee (or even predict) how it might work to create a user from there, but I suspect it doesn't use the custom user model.

In the meantime, you have total root control by shelling into the image, and then just querying users, collections, etc.

```bash
$ docker exec -it <uwsgi container> bash
$ python manage.py shell
```
Then

```python
from shub.apps.main.models import *
from shub.apps.users.models import *
User.objects.all() 
Collection.objects.all()
```
etc.

**Comment by vsoch** [comment]
Can you give me more detail about how exactly you tried deleting the collections owned by the admin interface created user?

**Comment by RonaldEnsing** [comment]
Thanks a lot for your quick reply. I tried deleting the collections that were owned by the regular user by logging in with the superuser / admin account on the web interface. Then I navigated to the 'collections' page. No 'settings' appear. However, for collections owned by the superuser / admin, 'settings' were available to remove the collection.

**Comment by vsoch** [comment]
Yes, I'm actually reproducing your issue now! I originally implemented it like this thinking that only owners should have access, but it does seem buggy that a superuser cannot. Would you expect a superuser to also be able to edit all settings?

**Comment by vsoch** [comment]
And what about staff (non superusers that are granted admin)?

**Comment by vsoch** [comment]
I'm going to have a PR to test for you asap! I agree this is an unintended bug. I'll post it here in just about a minute.

**Comment by vsoch** [comment]
okay here is a branch to test! https://github.com/singularityhub/sregistry/pull/230 I tested this locally, and  the superuser can see the settings. Let me know if it solves your issue, and thanks for pointing this out!

**Comment by RonaldEnsing** [comment]
> And what about staff (non superusers that are granted admin)?

I would expect that at least one of the two roles (either superuser, admin, or both) can do anything (like removing a collection). Not sure which one. I am also reading through https://github.com/singularityhub/sregistry/issues/89.

> okay here is a branch to test! #230 I tested this locally, and the superuser can see the settings. Let me know if it solves your issue, and thanks for pointing this out!

Thanks, I will!

**Comment by RonaldEnsing** [comment]
I can confirm that #230 solves it.

**Comment by vsoch** [comment]
Awesome! I'll merge, and you can update your branch with master, or wait (a little longer) for the automated build. Thanks again!
