### ISSUE TITLE
Create automated backup 

### ISSUE THREAD

**Issue by pianopwner** [singularityhub/sregistry#233]
I know that due to the shared volume setup of ./images :/var/www/images pushed and stored images are not lost when the registry containers are recreated. However in such a case, they do seem to disappear from the registry website UI (from the Containers tab). Is there a way to make them persist here upon container recreation?
Thanks!

**Comment by vsoch** [comment]
The “db” container serves as the database, so you can either change the configuration to use a different (non ephemeral) database or you can do a regular backup (eg with cron) using python manage.py dumpdata > db.json.  If you don’t want to dump credentials you can also specify which tables to dump! See https://docs.djangoproject.com/en/2.2/ref/django-admin/ and if you come up with a recipe that you like please share!  I would do some tests first with dumpdata and loaddata to make sure all is functioning as expected.

**Comment by pianopwner** [comment]
Thank you, I will look into this

**Comment by vsoch** [comment]
Sure! You know this would be fairly easy to add for the container to run (backup on a nightly basis of the containers / collections). Would this be of interest to you?

**Comment by pianopwner** [comment]
> Sure! You know this would be fairly easy to add for the container to run (backup on a nightly basis of the containers / collections). Would this be of interest to you?

Sorry, are you referring to setting up a cron job to dump the the data nightly? Or implying something else. Either way I am interested in this approach

**Comment by vsoch** [comment]
okay! I'll have a PR for you in a bit. To answer your question, yes - akin to how we reset collection / container limits, we would also have a nightly job in the uwsgi container to dump the tables we want to keep.

**Comment by vsoch** [comment]
Here is the PR with the branch to test: https://github.com/singularityhub/sregistry/pull/234.

There are complete instructions in the README [here](https://github.com/singularityhub/sregistry/pull/234/files#diff-52f92984f1b1a30208410378ecaf119c). I would clone that branch separately to test, meaning that you will:

 - bring up the containers
 - login and add a collection / container
 - shell into the uwsgi container and run the scripts/backup_db.sh
 - bring them down, remove them
 - bring up new containers (verify no collection)
 - shell into container, run scripts/restore_db.sh

More details are in that README! I've tested this all on my host and it's working as expected, let me know if you run into any issues.

**Comment by pianopwner** [comment]
Sorry for the delayed reply. This works for me, thank you for the work!
