### ISSUE TITLE
Pull down menu strings is not showed.

### ISSUE THREAD

**Issue by hpcs-isaka** [singularityhub/sregistry#236]
**Describe the bug**
Pull down menu strings is not showed in 'Permission needed to join team' selection field when New Team will be created.
Are there any corrections or workarounds?

**To Reproduce**
Click [Teams] in main menu - Click [Create a Team] button - Click and pull down in 'Permission needed to join team' field and click either 'Invite only. The user must be invited by an owner' or 'Open. Anyone can join the team without asking.'

**Expected behavior**
The menu string must be showed in the field after select either 'Invite only The user must be invited by an owner' or 'Open. Anyone can join the team without asking.'

![pulldownmenu](https://user-images.githubusercontent.com/48265052/66313307-1f655900-e94d-11e9-8950-824b00451ce0.png)

**Comment by vsoch** [comment]
So just to clarify - when you click the little button on the right - the "Permission needed to join team" field - you don't see any options? Or they are there, but the select isn't working?

Could you provide also:

 - open up your development console and look at the element to verify that the options aren't there (e.g., right click on element, Inspect, then open up the divs in the "Elements" tab - take a screen shot to show me what is there.
 - Also in devtools, go to the "Console" tab and verify there aren't any issues or errors (you can take a screen shot too if it's easier).

**Comment by hpcs-isaka** [comment]
Yes, I see the options 'Invite only The user must be invited by an owner' and 'Open. Anyone can join the team without asking.' and both are selectable and working well. It seems that the string of choices simply cannot be displayed.

Will the screenshot help you understand my condition?
![pulldownmenu_with_console](https://user-images.githubusercontent.com/48265052/66324826-27c78f00-e961-11e9-911f-4350c3a4a6bc.png)

**Comment by vsoch** [comment]
I can also see there is some JavaScript error (small red circle at the top right). Please show me the "Console" tab?

**Comment by vsoch** [comment]
And yes, that's what I'm trying to do :) The select is made possible by JavaScript, so if your browser (ad blocker or similar) is blocking something or there is some other error, it's not going to work.

**Comment by hpcs-isaka** [comment]
How about this screen shot?
![pulldownmenu_with_console_2](https://user-images.githubusercontent.com/48265052/66325394-25196980-e962-11e9-9edd-a10760669ea3.png)

**Comment by vsoch** [comment]
Thank you! Yes I think I can fix this. I'm working on another server this morning but will try to make some time this week.

**Comment by hpcs-isaka** [comment]
It was nice to have you understand the condition immediately! I would be happy to let you know when the fix work is finished.

**Comment by vsoch** [comment]
hey @hpcs-isaka I just pushed a fix - the container will take maybe 20-30 minutes to build and deploy to quay.io, but you can also clone the now master branch and build from scratch. Actually, it's just static files, so you should be able to pull down the templates and not need to rebuild the container.
