### ISSUE TITLE
singularity key push --url <> failing with 500 Internal Server error

### ISSUE THREAD

**Issue by asmi10** [singularityhub/sregistry#238]
musxtestvm006:~ # /infrastructure/sing/bin/singularity key push --url https://sregistrytest.hpc.caas.com/pks 248A205C1795F62CF6177C774438D434EDF9F541
ERROR:   push failed: key server did not accept PGP key: 500 Internal Server Error

In uwsgi logs I see below.

uwsgi_1      | Internal Server Error: /pks/add
uwsgi_1      | Traceback (most recent call last):
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1      |     return self.cursor.execute(sql, params)
uwsgi_1      | psycopg2.errors.UndefinedTable: relation "pgp_pgpkeymodel" does not exist
uwsgi_1      | LINE 1: INSERT INTO "pgp_pgpkeymodel" ("uid", "user_id", "file", "cr...
uwsgi_1      |                     ^
uwsgi_1      |
uwsgi_1      |
uwsgi_1      | The above exception was the direct cause of the following exception:
uwsgi_1      |
uwsgi_1      | Traceback (most recent call last):
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1      |     response = get_response(request)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1      |     response = self.process_exception_by_middleware(e, request)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
uwsgi_1      |     return view_func(*args, **kwargs)
uwsgi_1      |   File "./shub/plugins/pgp/views.py", line 62, in add
uwsgi_1      |     pgpkey = models.PGPKeyModel.objects.save_to_storage(None, keytext)
uwsgi_1      |   File "./shub/plugins/pgp/models.py", line 149, in save_to_storage
uwsgi_1      |     return self.create(uid=uid, user=user, file=fp)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 422, in create
uwsgi_1      |     obj.save(force_insert=True, using=self.db)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
uwsgi_1      |     force_update=force_update, update_fields=update_fields)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
uwsgi_1      |     force_update, using, update_fields,
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
uwsgi_1      |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
uwsgi_1      |     using=using, raw=raw)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
uwsgi_1      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
uwsgi_1      |     return query.get_compiler(using=using).execute_sql(return_id)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
uwsgi_1      |     cursor.execute(sql, params)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
uwsgi_1      |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
uwsgi_1      |     return executor(sql, params, many, context)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1      |     return self.cursor.execute(sql, params)
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
uwsgi_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
uwsgi_1      |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
uwsgi_1      |     return self.cursor.execute(sql, params)
uwsgi_1      | django.db.utils.ProgrammingError: relation "pgp_pgpkeymodel" does not exist
uwsgi_1      | LINE 1: INSERT INTO "pgp_pgpkeymodel" ("uid", "user_id", "file", "cr...
uwsgi_1      |                     ^
uwsgi_1      |
uwsgi_1      | [pid: 37|app: 0|req: 7/9] 10.216.137.221 () {38 vars in 1121 bytes} [Wed Oct  9 01:09:36 2019] POST /pks/add => generated 850 bytes in 21 msecs (HTTP/1.1 500) 3 headers in 128 bytes (1 switches on core 3)

**Comment by vsoch** [comment]
This means you didn’t restart containers to makemigrations and migrate for pgp. You can also shell into the uwsgi container and do this manually with python manage.py.

For the future, it’s helpful to read the error message, understand what’s going on, and then know next steps from that!

**Comment by vsoch** [comment]
@asmi10 any updates here? Are you still having issues?

**Comment by vsoch** [comment]
Closing, no response.
