### ISSUE TITLE
Container size map at collection level for large registries?

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#24]
On a registry with a very large number of containers the size map looks like a nice rainbow, but doesn't show much useful info since names can't be seen. Possibly create the map at collection level (sizes of each collection) when there are more than X containers?

![image](https://user-images.githubusercontent.com/4522799/29884198-4abfe2ec-8d78-11e7-84ed-a2cae7769ff1.png)

**Comment by vsoch** [comment]
haha I think that looks awesome :) What about something along the lines of:

 - make the labels more readable, or just "Mouse over to view" for large plots
 - allow the user to select some filtered subset to "zoom in on" (assuming we start with a collection)

**Comment by vsoch** [comment]
Hey @dctrud ! I just added a new view (to switch to collections given passing some threshold) so it will look like something simpler:

![image](https://user-images.githubusercontent.com/814322/29899680-ddf663f0-8dba-11e7-872c-1738cf358525.png)

You can set the threshold in your settings, instructions are here.

https://singularityhub.github.io/sregistry/deployment.html#visualizations

Could you test it out? And recommend a default? Also, I added a "save" button so the user can save the visualization as SVG. Also note that the "size" for the collection view refers to the mean size across all containers for that name. Also in the picture above, I had a bug with regard to the name, so the collection name is missing. I have fixed this, and was too lazy to re-take the screenshot :)

If this isn't detailed enough (eg, the plot is still crowded) we can switch to JUST showing the collections. Let me know your feedback!

**Comment by dctrud** [comment]
Hi - don't have ssh into home server from work, so I'll try it out this evening.

**Comment by dctrud** [comment]
I think it's still a bit crowded - but definitely better. Easier to see large to small containers without duplicates for tags. You can see at https://sregistry.randomroad.net/tools/sizes now.

**Comment by vsoch** [comment]
okay, I'll give a try at one more level up then, likely tomorrow! It looks still too crowded to me too.

**Comment by vsoch** [comment]
hey @dctrud ! I just updated the view so now we are *just* looking at collections. For my piddley 11 containers it looks like this:

![image](https://user-images.githubusercontent.com/814322/29992504-18b27a4a-8f6b-11e7-8442-43a13593b485.png)

Hopefully this will make random road's tree less crowded and more useful!

**Comment by vsoch** [comment]
@dctrud have you had a chance to test this yet?

**Comment by dctrud** [comment]
Yes - it's here: https://sregistry.randomroad.net/tools/sizes

I kind of think now at the collections level, mean size doesn't make that much sense? Total size of each collection is more intuitive?

**Comment by vsoch** [comment]
yeah that would make sense. Or maybe some kind of summary - mean, total, standard deviation? We'd want the viewer to get a sense for the collection, holistically.

**Comment by vsoch** [comment]
hey @dctrud - another round of changes! Now the collection view shows the TOTAL size, and further, if you click on a box (representing a collection) you see the zoomed in treemap of the containers for that collection (and then like the original view, clicking on one of those boxes goes to the container). There is also a link to a collection-specific map in the primary collection view, and I've limited the number of tags shown in the table to 50. I hope this resolves the issue! This has been a tough one :)

**Comment by dctrud** [comment]
Sounds great - I'll update my sregistry this evening. Sorry for slow replies. Have been pulled away from containery things onto other pressing stuff.

**Comment by dctrud** [comment]
@v - my public large sregistry is no more, but I think these changes look good if you want to close this.

**Comment by vsoch** [comment]
yes will do! And thank you for all the help getting this plot working as it should. Closing!
