### ISSUE TITLE
ldap auth not working

### ISSUE THREAD

**Issue by witlox** [singularityhub/sregistry#243]
**Describe the bug**

while configuring LDAP according to the documentation, there is an issue with the SECRET_KEY being set to 'empty' for some reason. Moving the secret to config.py allows the registry to start (not the case with the secret in secrets.py and LDAP enabled). After start, when trying to login, we get a system error:

ImportError: No module named 'django_auth_ldap'

**To Reproduce**

Enable LDAP and try to login

**Expected behavior**

Ability to login

If applicable, add versions and screenshots to help explain your problem.

version: current head (7f146a59d0396ab72d772217349e89646bea94b9)

**Comment by vsoch** [comment]
hey @witlox - the secret key is totally separate from LDAP itself, it's a requirement for all django deployments to encrypt stuffs from the back to front end (see [docs here](https://stackoverflow.com/questions/7382149/purpose-of-django-setting-secret-key)). You likely need to go carefully through the [setup instructions](https://singularityhub.github.io/sregistry/docs/install/settings#secrets), specifically here is instructions for how to generate the key and add to a secrets.py file under shub/settings that you copy from shub/settings/dummy_secrets.py.

**Comment by witlox** [comment]
hey @vsoch , my bad, I missed the part where I needed to recompile the container with LDAP support. It's working fine, nice job 👍
