### ISSUE TITLE
unable to pull the container from sregistry

### ISSUE THREAD

**Issue by ashwinidr3** [singularityhub/sregistry#245]
when i try to generate a link a temporary link to download the container, i get the error "There was a problem sharing your container! Submit an issue for help. 7 days. ". also i am unable to download container via other methods given in usage tabs.

the following are the errors
1.singularity run shub://container.page/test/lolcow:latest
INFO:    Downloading shub image
FATAL:   Failed to get manifest from Shub: No response received from singularity hub

2. singularity pull --library http://host test/lolcow:latest
FATAL:   While getting image info: the requested image was not found in the library

I went through the previous issues and tried the solution, which is also not working
singularity pull $(curl http://host/api/container/test/lolcow:latest | jq --raw-output .image)
bash: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   342  100   342    0     0   1038      0 --:--:-- --:--:-- --:--:--  1045
(23) Failed writing body
Usage:
  singularity [global options...] pull [pull options...] [output file] <URI>

also i have converted my account to super user and admin. but i do not see the admin tab in GUI even after restarting docker-compose.

any help is appreciated, Thanks in advance!!

**Comment by vsoch** [comment]
Did you set the remote endpoint to be your registry? It sounds like you are querying the main Singularity Hub. If so, are you using https?

**Comment by ashwinidr3** [comment]
Thanks for your reply , I have indeed not set up remote endpoint. So I
tried to install sregistry through GitHub but I get the error saying setup
tools is too old.

The python version I am using is 2.7.8 . Does the install support this
version?

**Comment by vsoch** [comment]
Ah, so a few notes!
 
 - sregistry client requires Python 3+. Python 2 is pretty much end of life so I'd suggest you consider upgrading.
 - the sregistry client does not mean you create a remote server, it's a command line client that would let you push to a Singularity Registry server (if you were running one) or another remote endpoint.
 - Singularity Hub != a Singularity Registry Server, you cannot push to Singularity Hub, but rather you build from GitHub repos.

Let me know if you have any other questions! If you mainly want to build images, I'd highly recommend automated builds on Docker Hub, and then pulling down to Singularity containers like:

```bash
singularity pull docker://vanessa/salad
```
The reason is so you can kill two birds with one stone, and have a Docker and Singularity container.

**Comment by ashwinidr3** [comment]
Yes, I do understand singularity hub is different from sregistry.I have
configured sregistry on a host. I have used ldap authentication.

Now I would like to be able to pull and push containers into the registry I
configured. Right now i get the error which I have specified previously.

Since I am running behind time, I could not go through many documents to
resolve the issue. And I am not aware of what all things are necessary to
get this done.

Could you please help me further with the procedure.

Thank you
Ashwini

**Comment by vsoch** [comment]
I can't help with LDAP, but if you want to use the sregistry client you absolutely need Python 3. If you want to use the Singularity client, if you have 3.3.0 and up you can use the library:// push endpoint just released today (Singularity Registry Server 1.1.10). https://singularityhub.github.io/sregistry/docs/client#singularity-push. For this second option, you will need to have https for your server, as Singularity requires it.

**Comment by ashwinidr3** [comment]
I have already configured LDAP and works fine.
I just upgraded the python to version 3.7.4 and downloaded sregistry-cli. i
have trouble installing it.

python setup.py install
Download error on https://pypi.org/simple/pytest-runner/: unknown url type:
https -- Some packages may not be found!
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
Download error on https://pypi.org/simple/: unknown url type: https -- Some
packages may not be found!
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    entry_points = {'console_scripts': ['sregistry=sregistry.client:main']})
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py",
line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py",
line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line
724, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py",
line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py",
line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py",
line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line
791, in fetch_build_egg
    return cmd.easy_install(req)
  File
"/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py",
line 673, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for
Requirement.parse('pytest-runner')

The Proxy is set properly. i am not sure what else i am missing

**Comment by vsoch** [comment]
pytest-runner is there https://pypi.org/simple/pytest-runner/ so I'm guessing you are having some issues with your proxy or using ssl. I would verify this on some other host that you aren't behind the proxy and go from there. I unfortunately can't debug your proxy for you, but the first error message

```
Download error on https://pypi.org/simple/pytest-runner/: unknown url type:
https -- Some packages may not be found!
```
Tells us that this is the issue. It sounds similar to this https://github.com/collective/buildout.python/issues/55 which suggests that libraries for ssl are missing.

**Comment by ashwinidr3** [comment]
Ok, I will work on this . Meanwhile I have upgraded the singularity version
to 3.4 . So to use singularity client I need to configure the server with
https .I see there are scripts to generate ssl in the sregistry itself.

Could you please point me to the document which gives information about
placing ssl certificate in registry etc if it already exists?

**Comment by vsoch** [comment]
I usually use certbot, instructions -> https://singularityhub.github.io/sregistry/docs/install/https

**Comment by ashwinidr3** [comment]
Thanks for the link, I tried to use certbot but getting the following error

./certbot-auto certonly --nginx -d "${DOMAIN}"  --email "${EMAIL}"
--agree-tos --redirect
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sregistrytest.com
Using default address 80 for authentication.
Using default address 80 for authentication.
nginx: [error] invalid PID number "" in "/var/run/nginx.pid"
Waiting for verification...
Challenge failed for domain sregistrytest.com
http-01 challenge for sregistrytest.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: sregistrytest.com
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up A for
   sregistrytest.com.

not sure why i am getting DNS error. when i do host -a sregistrytest.com,
it shows up with the correct IP.

is there any way to make the sregistry pull work with HTTP as i am reaching
the dead end all possible ways with http!!
sregistry-cli - is not getting installed due to the issue i stated in
previous mail.
https - having trouble creating the certs

i cannot disable https in singularity (remote.go doc)since it  is not
installed through source.

could you please help with any work around untill i solve this issue?
I need to get it running ASAP

Thank you

**Comment by vsoch** [comment]
That needs to be run on the server with a local/separate Nginx, and not in the container. The containers should all be stopped.

**Comment by vsoch** [comment]
I’ve provided the steps that worked for me, if it doesn’t work for you, then you can search for possible sources of the error that you are getting or use another method to manage certificates. I’ve used tiny-acme before with success too, but I find certbot easier.

And of course your DNS should also be configured for https, that’s outside the scope of sregistry.

**Comment by ashwinidr3** [comment]
yes , i stopped the docker compose before starting nginx.

**Comment by ashwinidr3** [comment]
Thank you, I will try other ways to create certificate!

**Comment by ashwinidr3** [comment]
I managed to install sregistry on the host .

I am getting the following error when i try to push.

sregistry push --name vanessa/tacolicious --tag gobacktosleep $(sregistry
get vsoch/hello-world)
[client|registry] [database|sqlite:////root/.singularity/sregistry.db]
Traceback (most recent call last):
  File "/usr/local/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.2.31', 'console_scripts', 'sregistry')()
  File
"/usr/local/lib/python3.6/site-packages/sregistry-0.2.31-py3.6.egg/sregistry/client/__init__.py",
line 323, in main
    extra=extra)
  File
"/usr/local/lib/python3.6/site-packages/sregistry-0.2.31-py3.6.egg/sregistry/client/push.py",
line 34, in main
    tag=args.tag)
  File
"/usr/local/lib/python3.6/site-packages/sregistry-0.2.31-py3.6.egg/sregistry/main/registry/push.py",
line 47, in push
    names = self._add_https(names)
  File
"/usr/local/lib/python3.6/site-packages/sregistry-0.2.31-py3.6.egg/sregistry/main/registry/__init__.py",
line 67, in _add_https
    if not q['registry'].startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'

am i missing something here?

Thanks in advance

**Comment by vsoch** [comment]
Taking a look!

**Comment by vsoch** [comment]
Could you please show me your sregistry secrets (without the token) you were instructed to export to $HOME/.sregistry?

**Comment by ashwinidr3** [comment]
Thanks for the quick response. I will share it in a while. I don't have my
laptop handy right now.

**Comment by vsoch** [comment]
This would happen if the user doesn't provide a base in the environment, their secrets, or via the image. What I've done is pushed a PR that should at least catch the issue and tell you what's wrong. Please test https://github.com/singularityhub/sregistry-cli/pull/248 and read about the needed credentials https://singularityhub.github.io/sregistry/docs/accounts/credentials

**Comment by ashwinidr3** [comment]
Please find the secrets.py file

# The URI to our LDAP server (may be ldap:// or ldaps://)

AUTH_LDAP_SERVER_URI = "hostname"

# DN and password needed to bind to LDAP to retrieve user information
# Can leave blank if anonymous binding is sufficient

AUTH_LDAP_BIND_DN = "cn=Linux_name,ou=User Accounts,ou=User
Directory,dc=linux,dc=org,dc=com"

AUTH_LDAP_BIND_PASSWORD = "password"

# Any user account that has valid auth credentials can login
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=User Accounts,ou=User
Directory,dc=linux,dc=shell,dc=com",
                                   ldap.SCOPE_SUBTREE,
"(sAMAccountName=%(user)s)")

AUTH_LDAP_GROUP_SEARCH = LDAPSearch("ou=General Groups,ou=Group
Directory,dc=linux,dc=shell,dc=com",
                                    ldap.SCOPE_SUBTREE,
"(objectClass=group)"
                                    )

i will try to run the test which u have specified earlier

**Comment by vsoch** [comment]
I think you are forgetting to export your sregistry secrets - different from the secrets.py file in settings. You need to go to your username -> Token and export the json there to $HOME/.sregistry. It's written in full here https://singularityhub.github.io/sregistry/docs/accounts/credentials

Please, generally you should read and follow the documentation, because you are missing major steps...

**Comment by ashwinidr3** [comment]
phew, it worked now finally!!

sorry i did not pick up on what u meant by secrets file.I had setup the
secrets file before, the issue was about the syntax in secrets file.

yes u right , i should have followed the document properly , but i was
working on multiple things at the same time so i did miss few things while
juggling between pages.

Thanks a lot for your patience and all the help . much appreciated :)

**Comment by vsoch** [comment]
Glad to help! You know, even with multiple things, it's sometimes worth those few extra minutes, because they ultimately wind up saving you many more.
