### ISSUE TITLE
Broken links in Tools page

### ISSUE THREAD

**Issue by Aneoshun** [singularityhub/sregistry#262]
Hey @vsoch, 

I have noted that the following three API links on the Tools page are broken on my side:
- Documentation
- Swagger API
- Restful Schema

Is it the case for you too?

**Comment by vsoch** [comment]
Sorry power is out I can’t look now.

**Comment by Aneoshun** [comment]
Well, that's a fair reason.  ^^
It's not urgent, I am just raising issues as soon as I see something that does not sounds good.

**Comment by vsoch** [comment]
okay I found a plug and free coffee wife (god this sucks, I had to leave my apartment complex) but I can take a look!
