### ISSUE TITLE
Incorrect example in usage page

### ISSUE THREAD

**Issue by Aneoshun** [singularityhub/sregistry#263]
Hey @vsoch , 

Another small, non-urgent bug. 
On this line, I think the container name is missing. 
https://github.com/singularityhub/sregistry/blob/9b9c0f8e50257d6b70a16ca6e071cd3e493283db/shub/apps/main/templates/collections/collection_commands.html#L46

Also, I am not sure we can use `shub`. In my case it does not work. I have to use `library` while having the right remote configured (and in this case, the `DOMAIN_NAKED` is not necessary).

**Comment by vsoch** [comment]
For shub, the domain would be necessary. For library, since the domain is configured with singularity, it wouldn't be.

**Comment by vsoch** [comment]
I'm fairly sure I opened this as an issue with Singularity, and I'd bet they haven't fixed it. I'll remove that line from the docs for now.
