### ISSUE TITLE
[ VIEW ] Summary of container storage size / distribution

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#3]
This might actually be good use for a kind of tree map:

https://bl.ocks.org/mbostock/e6962a152275373f8504

**Comment by dctrud** [comment]
There's a nice disk usage treemap example here that might be useful: https://github.com/geekoftheweek/disk-treemap

**Comment by vsoch** [comment]
okay, this is done! It's not about filesystem analysis (we are inside a docker container, anyway) but rather the size of the containers relative to one another.

![image](https://user-images.githubusercontent.com/814322/29499163-d398e7aa-85d8-11e7-9df2-874699b9a45d.png)
