### ISSUE TITLE
Feature request: Users deciding visibility/privacy

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#30]
Dear all,

I'm playing with the sregistry, and I would like to have the registry working for my project. This will expose a bunch of images submitted by users, but some of them could have private data or source code, tetc.

I have seen the `PRIVATE_ONLY` variable in the config file in config file and #21 . it allow admins to decide if they want to have all collection public or private.

Can users by themselves to decide which images can be public or not?

I would like to have this feature, and the `PRIVATE_BY_DEFAULT=yes/no` instead of the `PRIVATE_ONLY` variable.

How it sounds for you?

BR,
Víctor.

**Comment by vsoch** [comment]
Hi Victor. This is a great idea! I think this might already bee implemented as you would want. Could you try going to a collection view as the owner, and looking at the "administration" dropdown? You should see a toggle to make a (currently) public collection private and vice verse:

![image](https://user-images.githubusercontent.com/814322/31274589-5e3740bc-aa48-11e7-9612-93e05554c0f4.png)

And I can easily expose a second variable `PRIVATE_BY_DEFAULT` that changes this default setting. With this satisfy what you are looking for?

**Comment by victorsndvg** [comment]
Yes, it's perfect for me!

Now I'm getting into troubles with the DB, but I will check as soon as possible.

Thanks again! ;)

**Comment by vsoch** [comment]
ok, I just added another setting to distinguish being able to enforce private only (`PRIVATE_ONLY`) and then switching the default to be private but still allowing users to switch to public (`DEFAULT_PRIVATE`). I didn't do rigorous testing, so let me know if it works!

https://singularityhub.github.io/sregistry/deployment.html#registry-private

**Comment by victorsndvg** [comment]
Thanks!

I will reopen the issue if I find any issue.
