### ISSUE TITLE
Unable to push image to library after introducing minio backend

### ISSUE THREAD

**Issue by RonaldEnsing** [singularityhub/sregistry#307]
The error message I get is:
`FATAL:   Unable to push image to library: error uploading image: PUT http://127.0.0.1:9000/sregistry<credential, request, signature> giving up after 5 attempts`

I've tried older versions of sregistry, and I run into the issue after the merge of this PR: https://github.com/singularityhub/sregistry/pull/298
I am using the same image and command to push the image when I tried different versions of sregistry. Could https://github.com/singularityhub/sregistry/pull/298 be causing this? I've also noticed that the date and time in the request is incorrect. Possibly due to time zones, because it differs exactly a few hours from the actual time. Could incorrect configuration of time zones be related?

**Comment by vsoch** [comment]
There are lots of variables at play and I’ll need more information to figure out what’s up.

Did you try cloning and creating an sregistry not on top of an old one? That would determine if it’s an issue with migration.

Are the needed environment variables set, have you carefully gone through the new docs for using Minio?

Is the new Minio container running without issue and can you follow instructions in the docs to verify connection to the main server?

Do you have a folder created for Minio images?

Are you using the library endpoint?

I need to know as much as possible beyond “there is an error” so I can reproduce or at least follow. There have been several users that deployed the Minio version successfully so I suspect it’s an upgrade issue. 

Finally are you using Singularity library endpoint to push?

**Comment by RonaldEnsing** [comment]
I've already had sregistry running. So this might indeed be an upgrade issue. I updated sregistry to version 2.2.13 (commit: `5a2cc89ede41bdeb3bab035464a8d5b9523cc1bc`).

I've found out that commit `401c1b8cf5a453e8bf059126e4b6381cf8ef3aa8` breaks it by testing various commits using binary search.

I haven't changed anything on the client side.

Is Minio a required replacement or optional? I haven't configured anything for Minio indeed.

**Comment by vsoch** [comment]
> Is Minio a required replacement or optional? I haven't configured anything for Minio indeed.

That is very likely the issue! It's not required, but the speedup / memory save is huge because it adds multipart upload.I would highly recommend.

**Comment by RonaldEnsing** [comment]
If I upgrade to using minio, will this be backwards compatible with my previous singularity image uploads?

**Comment by vsoch** [comment]
You would have two separate storages - one the older one in images, and one in minio-images. I created it so both could persist but I can’t guarantee that because I don’t have an active registry to test. Maybe you could set up a dummy registry, push some containers, do the upgrade and test everything out to your liking?

**Comment by vsoch** [comment]
If you haven’t read here -> https://singularityhub.github.io/sregistry/docs/install/server#storage

**Comment by RonaldEnsing** [comment]
Thanks. There seems to be a dead link to https://singularityhub.github.io/install-builders in there, by the way.

**Comment by vsoch** [comment]
I don’t even remember what that is supposed to link to - perhaps https://singularityhub.github.io/sregistry/docs/plugins/google-build?

**Comment by RonaldEnsing** [comment]
> You would have two separate storages - one the older one in images, and one in minio-images. I created it so both could persist but I can’t guarantee that because I don’t have an active registry to test. Maybe you could set up a dummy registry, push some containers, do the upgrade and test everything out to your liking?

That's basically what I did before creating this issue. If I do that, I run into `FATAL: Unable to push image to library: error uploading image: PUT http://127.0.0.1:9000/sregistry<credential, request, signature> giving up after 5 attempts`.

**Comment by vsoch** [comment]
Yes but you still need to configure Minio for the containers to work!

**Comment by RonaldEnsing** [comment]
So I assume that the containers should be up before I do:
`./mc config host add myminio http://127.0.0.1:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY`.
Is that correct?
Otherwise I get:
`mc: <ERROR> Invalid access key <key>. Invalid arguments provided, please refer mc <command> -h for relevant documentation.`

**Comment by vsoch** [comment]
Yes, that would be logical! Make sure that your Docker-compose was updated to include the Minio container, and when you shell inside the others you can see the needed envars.

**Comment by RonaldEnsing** [comment]
If I do `docker compose up -d` I get the following error:
```
Removing sregistry_uwsgi_1
Starting sregistry_minio_1 ... 
sregistry_redis_1 is up-to-date
Starting sregistry_minio_1
Starting sregistry_minio_1 ... done
Recreating 20d5948f7b23_20d5948f7b23_sregistry_uwsgi_1 ... 
Recreating 20d5948f7b23_20d5948f7b23_sregistry_uwsgi_1 ... error

ERROR: for 20d5948f7b23_20d5948f7b23_sregistry_uwsgi_1  Cannot start service uwsgi: Cannot link to a non running container: /sregistry_minio_1 AS /sregistry_uwsgi_1/minio

ERROR: for uwsgi  Cannot start service uwsgi: Cannot link to a non running container: /sregistry_minio_1 AS /sregistry_uwsgi_1/minio
ERROR: Encountered errors while bringing up the project.
✗ - status code 1
```

**Comment by vsoch** [comment]
This seems like the creation error mentioned above- is the Minio environment file there, and did you remove previous containers first and did you either rebuild or pull the previous?

**Comment by RonaldEnsing** [comment]
The `.minio-env` is there. I modified the value of the `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY`.

I stopped all containers and removed everything to start with a clean slate:
```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
```
So I even removed my database with users, permissions and collections.

Then I did `docker compose up -d`, resulting in the error I posted.

**Comment by vsoch** [comment]
What was the error that stopped Minio from going up and running? Also it shouldn’t have said removing the uwsgi container if you already did that. I still think it’s an issue with the containers you are starting with.

**Comment by RonaldEnsing** [comment]
Maybe my understanding is not correct. As far as I know, Minio should go up using `docker compose up -d` as well. The error I get is the one I posted here: https://github.com/singularityhub/sregistry/issues/307#issuecomment-642726352.

**Comment by vsoch** [comment]
Right, my comment is this line:
```
Removing sregistry_uwsgi_1
```
Should not appear if the container did not exist. I'm sorry that you are having trouble - it's hard to help you given that I only have a marginal idea of what you did, and the error messages you are showing do not logically coincide with the commands reported. Could you please start from scratch and provide a dummy example, with every step and change, so that I can reproduce your issue? For example, I see no command that would pull an updated container version, or rebuild. If I cannot reproduce I'm afraid I can't help, and this just looks like an issue of creating / updating containers.

**Comment by RonaldEnsing** [comment]
Thank you for your suggestion @vsoch. After going through this from scratch I noticed that the error I reported here: https://github.com/singularityhub/sregistry/issues/307#issuecomment-642726352, is a result from modifying the `.minio-env`. If I leave these to the default values, I do not run into this error. Any idea why that is the case? I think I may have to take a closer look into how Minio works.

When I start from scratch and use the default values for `.minio-env`, I run into what I posted here: https://github.com/singularityhub/sregistry/issues/307#issue-635501210.

These are the steps I performed to remove images and containers:
```
docker stop $(docker ps -aq)
docker container rm $(docker container ls -aq)
docker rmi $(docker images -q)
```
Then I upgraded sregistry to include the usage of minio.
`git checkout 5a2cc89ede41bdeb3bab035464a8d5b9523cc1bc`

I only modified some settings in my nginx conf, and I verified that the web interface is accessible.

I brought the containers up using:
`docker-compose up -d`

A `singularity push` results in the error I posted here: https://github.com/singularityhub/sregistry/issues/307#issue-635501210.

**Comment by vsoch** [comment]
@RonaldEnsing I can't reproduce your error, and I'll provide you with the exact commands I did.

Pull repo, build a new container
```
git clone git@github.com:singularityhub/sregistry
cd sregistry
docker build -t quay.io/vanessa/sregistry
```

You of course could just repull that container, since they are automated builds on quay.io. Then I updated the minio environment file

```
MINIO_ACCESS_KEY=somenewpwd
MINIO_SECRET_KEY=somenewpwd
MINIO_ACCESS_KEY_OLD=minio
MINIO_SECRET_KEY_OLD=minio123
```
Note that the old key MUST stay the same. I then copied my previous secrets.py file (from another repo clone)
```
$ cp /home/vanessa/Desktop/Code/sregistry/shub/settings/secrets.py shub/settings/secrets.py
```

Then brought up the containers (forcing pull of the other ones since I don't have them locally)

```bash
docker-compose up -d
```
Containers are running:

```
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS              PORTS                         NAMES
1e5b265873f1        quay.io/vanessa/sregistry         "python /code/manage…"   About a minute ago   Up About a minute   3031/tcp                      sregistry_worker_1
b0d13c5ace30        quay.io/vanessa/sregistry_nginx   "nginx -g 'daemon of…"   About a minute ago   Up 46 seconds       0.0.0.0:80->80/tcp, 443/tcp   sregistry_nginx_1
9f728d1c6f87        quay.io/vanessa/sregistry         "python /code/manage…"   About a minute ago   Up About a minute   3031/tcp                      sregistry_scheduler_1
39015c331d57        quay.io/vanessa/sregistry         "/bin/sh -c /code/ru…"   About a minute ago   Up About a minute   3031/tcp                      sregistry_uwsgi_1
6d9026d878d8        minio/minio                       "/usr/bin/docker-ent…"   About a minute ago   Up About a minute   0.0.0.0:9000->9000/tcp        sregistry_minio_1
56c495a39403        redis:latest                      "docker-entrypoint.s…"   About a minute ago   Up About a minute   6379/tcp                      sregistry_redis_1
f2f14bac9662        postgres                          "docker-entrypoint.s…"   About a minute ago   Up About a minute   5432/tcp                      sregistry_db_1
```
Then I had to recompile singularity changing the line in remote/remotes.go to allow http (not shown, it's in the docs). And then login to my remote with the new token:

```
$ singularity remote use DinosaurCloud
INFO:    Remote "DinosaurCloud" now in use.
$ singularity remote login
INFO:    Authenticating with default remote.
Generate an API Key at https://127.0.0.1/auth/tokens, and paste here:
API Key: 
INFO:    API Key Verified!
```

Then I created a collection and pushed to it:
```
$ singularity push -U --library http://127.0.0.1 busybox_latest.sif library://vsoch/collection/busybox:latest
WARNING: Skipping container verifying
764.0KiB / 764.0KiB [==============================================================================] 100 % 34.4 MiB/s 0s
```
Worked without a hitch, so I cannot reproduce your issue.

![image](https://user-images.githubusercontent.com/814322/84524366-19233b80-ac97-11ea-8f29-88184b50320c.png)

**Comment by RonaldEnsing** [comment]
Thanks a lot @vsoch. I now suspect that this may be caused by not having port 9000 open on the server. Once I run everything locally, both the client doing the push and the sregistry server, the push works.

**Comment by RonaldEnsing** [comment]
Could this [1] be a race condition? It works after another `docker-compose up -d` attempt.

[1] https://github.com/singularityhub/sregistry/issues/307#issuecomment-642726352

**Comment by vsoch** [comment]
Because of the presence of
```
Removing sregistry_uwsgi_1
```
and then because it had trouble creating the new uwsgi, my best guess is that it could be, but it would also be specific to your particular case of re-creating containers, which commonly has this error when old links no longer work. I'd want to see the error/issue happen without the situation of needing to remove / recreate containers.

**Comment by RonaldEnsing** [comment]
So port 9000 should be accessible to the client?

**Comment by vsoch** [comment]
Yes I think so, would it help to read about Minio on your own? https://docs.min.io/docs/minio-quickstart-guide.html Have we addressed your original issue?

**Comment by RonaldEnsing** [comment]
Sure. I was not sure if the sregistry server interacted with minio on the backend only, but I guess it does not. Thanks. I think we can close this issue.

**Comment by vsoch** [comment]
Sure thing. You can look at the code if you are curious too... https://github.com/singularityhub/sregistry/blob/master/shub/apps/library/views/minio.py
