### ISSUE TITLE
Error while installation Installation: Web Server and Storage

### ISSUE THREAD

**Issue by atharvnagarikar** [singularityhub/sregistry#325]
**Describe the bug**
After installing mc in the singularity registry server I was asked to add secret and access key and I encountered following error
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://127.0.0.1:9000/probe-bucket-sign-djq2g90156l6/?location=": dial tcp 127.0.0.1:9000: connect: connection refused.
**To Reproduce**
![errorsrs](https://user-images.githubusercontent.com/66713062/95746316-394e2000-0cb4-11eb-970b-b2cb35e86c21.PNG)

**Expected behavior**

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
You should be defining the secret key in the Minio-env file that is referenced in the Docker compose file before bringing anything up, I don’t know what you are doing here. Please read the documentation and follow instructions, that’s what it’s there for.

**Comment by atharvnagarikar** [comment]
I added secret key in minio-env file but it still gives same erre
