### ISSUE TITLE
Redirect link issue 

### ISSUE THREAD

**Issue by atharvnagarikar** [singularityhub/sregistry#328]
I follow all the steps for the singularity registry but I'm facing an error in the redirect link while trying to login into the UI.
I'm getting what king of a redirect to provide in Gitlab
![err1](https://user-images.githubusercontent.com/66713062/98229290-bd2bbd00-1f7f-11eb-8aa8-e71319fc029f.PNG)
![err2](https://user-images.githubusercontent.com/66713062/98229295-be5cea00-1f7f-11eb-8052-dad1a662dd0c.PNG)

 Oauth

**Comment by vsoch** [comment]
It’s usually an issue of http vs https or even just a trailing slash.

**Comment by atharvnagarikar** [comment]
so what Should I use

**Comment by atharvnagarikar** [comment]
I use redirect link as http://127.0.0.1/complete/gitlab

**Comment by vsoch** [comment]
As I mentioned, the most common issues are trailing slashes. Aside from that, it's out of scope for me to debug this for you so you might consider opening an issue to ask for help from GitLab https://docs.gitlab.com/ee/api/oauth2.html#help-and-feedback

**Comment by atharvnagarikar** [comment]
I solved it and thanks for the help
