### ISSUE TITLE
Singularity remote login issu

### ISSUE THREAD

**Issue by atharvnagarikar** [singularityhub/sregistry#330]
I follow the procedure for the singularity registry server and I got the GUI for the localhost, the only issue I'm facing is during the singularity remote login. According to the procedure if we want to have remote login with localhost then it is necessary to make  changes in the 'remote.go' file and I did it and recompile the singularity. But I'm facing the following issue shown in the screenshots . Do check it and let me know
![err3](https://user-images.githubusercontent.com/66713062/102333345-4d174a80-3fb3-11eb-95f6-21e02430b994.PNG)

**Comment by vsoch** [comment]
That's correct, if you want it to work without https you'd need to change remote.go and recompile.

**Comment by atharvnagarikar** [comment]
but I'm facing above error

**Comment by vsoch** [comment]
What error does the server say?

**Comment by atharvnagarikar** [comment]
I shared the screenshot , please check it

**Comment by atharvnagarikar** [comment]
After making changes in the remote.go file it should reflect changes while using singularity remote I mean it should show HTTP://127.0.0.1:9080/auth/token instead of HTTPS://127.0.0.1:9080/auth/token and should very the token
![err4](https://user-images.githubusercontent.com/66713062/102337411-725a8780-3fb8-11eb-971b-769a19b90513.PNG)
![err3](https://user-images.githubusercontent.com/66713062/102337432-78506880-3fb8-11eb-87be-dcc7fed3150c.PNG)

**Comment by vsoch** [comment]
I need to see the Singularity Registry Server logs, `docker-compose logs uwsgi`.

**Comment by atharvnagarikar** [comment]
ok

**Comment by atharvnagarikar** [comment]
![us1](https://user-images.githubusercontent.com/66713062/102349701-c28e1580-3fc9-11eb-89db-e0127e714c53.PNG)
![us2](https://user-images.githubusercontent.com/66713062/102349706-c457d900-3fc9-11eb-86b6-8dcfc7b731dd.PNG)
![us3](https://user-images.githubusercontent.com/66713062/102349713-c5890600-3fc9-11eb-90c8-c30bd72de01f.PNG)

**Comment by vsoch** [comment]
I don’t see the request there - you should call the endpoint, and then see the request in that output.

**Comment by atharvnagarikar** [comment]
I didn't get it, can you please elaborate the above statement

**Comment by vsoch** [comment]
1. Make the request to login, see the error message in the console (as you did)
2. *Then* do `docker-compose logs uwsgi` and `docker-compose logs nginx` - you should see a failed record of the request in both.

For the image you provided, I don't see any evidence that you pinged the endpoint that is erroring, which suggests your requests aren't hitting the server at all, or you shared a version of the logs that doesn't include it. What I do see is running migrations, and then logging in with gitlab, and then migrations again. I don't see any indication of hitting the remote login endpoint, which is the first issue here.

**Comment by atharvnagarikar** [comment]
yes ma'am that is what the issue is, as I told you in the above comments that it ping to https://127.0.0.1/auths/token instead of http://127.0.0.1/auths/token after making changes in the remote.go file , what is the reason behind I'm not getting it at all

**Comment by atharvnagarikar** [comment]
yes ,that is what the issue is, as I told you in the above comments that it pings to https://127.0.0.1/auths/token instead of http://127.0.0.1/auths/token after making changes in the remote.go file, what is the reason behind I'm not getting it at all

**Comment by vsoch** [comment]
If it’s pinging https then you either didn’t compile it correctly or aren’t using the binary  that you think you are. I can’t debug this for you, you’ll have to figure it out.

**Comment by atharvnagarikar** [comment]
I followed  the same procedure for re-compile which is  provided at the singularity website

**Comment by vsoch** [comment]
You could try debugging by adding a print statement for the url being used. I can’t offer help further.

**Comment by atharvnagarikar** [comment]
thanks a lot for your help, the issue has been resolved

**Comment by vsoch** [comment]
Could you please share what you figured out to be the problem and solution, for future users that encounter something similar?

**Comment by vsoch** [comment]
The user is unfortunately not providing any detail about what the problem was, which is not helpful for future folks that might run into it. Closing issue.
