### ISSUE TITLE
PGP Keystore

### ISSUE THREAD

**Issue by vladdoster** [singularityhub/sregistry#338]
What exactly is the intended purpose of the PGP Keystore plugin?

I assume it's security related but the example makes it seem that it enables querying sregistry from the CLI? 

Could you elaborate? I will add a short blurb on the docs if you deem reasonable.

Thanks in advance!

**Comment by vladdoster** [comment]
Btw, even though this is a __question__ issue, it wasn't given a label. I will see if it's possible to do and try to add it as well.

#automation

**Comment by vsoch** [comment]
Oh, I think this was already added and can be closed :) 

https://singularityhub.github.io/sregistry/docs/plugins/pgp

The idea is that when you sign a container, you can also push the keys to the registry.
