### ISSUE TITLE
Promote/create Debian/Ubuntu packages for installation

### ISSUE THREAD

**Issue by smoe** [singularityhub/sregistry#35]
I found https://github.com/singularityhub/sregistry/blob/master/scripts/prepare_instance.sh to be an interesting mix between Ubuntu specifica and general install instructions with pip and the downloaded Anaconda. Is Anaconda truly required or could we also just work with a regular installable (and deinstallable (!)) system-wide installed python?

The two pip-installed packages do no require the extra pip, for instance https://packages.debian.org/search?keywords=python-ipaddress or https://packages.debian.org/search?keywords=python-oauth2client, so these packages I also expect in Ubuntu. Does this possibly mean that pip does not need to be installed, either?

I can update or backport for you as required.

**Comment by vsoch** [comment]
hey @smoe ! Anaconda isn't necessary, it's just the distribution of python I tend to go for in the case of needing nicely packaged numerical libraries. The basic dependencies are:

 - docker-compose (needs the python libraries on the host)
 - git to pull repo
 - docker

And it doesn't matter so much how you choose to install, or the host that is your preference. I included the prepare instance script (the one that I use) if others were interested, the user might already have these things installed (eg system python) and just need to install Docker.

pip as a package manager is always my preference for installing, but to each his own! :)

**Comment by smoe** [comment]
Thank you for your swift reply, @vsoch. I had very much hoped you would say something along those lines - since this means that I have done everything right-enough for my test run.

Newbies like me just don't know about version dependencies and may redundantly install bits and pieces. Please allow that I prepare a pull request that would then be minimalistic and leave all docker-specific installation to ... well docker: The requirements docker needs will be auto-fetched from the repository (been there a few days ago). This means that you can remove all installation-related lines of python/python-modules/pip from that script. Your software then looks even more simple to install and better understandable for users of other distributions.

Please allow that I eventually come up with a pull request with something that is both minimalistic and working for me.

**Comment by vsoch** [comment]
hey @smoe ! I think I just pushed change that address your concern - I point the user to the Docker and Docker compose installation pages for instructions specific to the distribution. When you are willing to dive in again, please try the install and bringing up the image (and you could skip building and it will pull the image from docker hub). Let me know what needs work (and a pull request with suggestions would be fantastic!) But definitely I can do most of the heavy lifting to fit the issues that you find.

If you need to remove some previously built erroneous image, try:

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

It's great you are learning some too! Docker is... a bit weird. It took me definitely some time to get the hang of it.

**Comment by smoe** [comment]
I cannot see it - have you pushed?

**Comment by smoe** [comment]
Found it https://github.com/singularityhub/sregistry/blob/master/docs/install.md - reads very nice, indeed! Many thanks!

**Comment by vsoch** [comment]
I think we resolved this! Thanks again @smoe !
