### ISSUE TITLE
docs missing instructions for credential file `.sregistry` and bug with client inspect

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#37]
Hi,

after installing the web server and authenticate with social auth, now I want to try to push/pull images using sregistry.

I build singularity-python locally as explained in the `Singularity` file. Now I've access to `sregistry`.

How can I use it properly?

First, I get the "no secrets file exists" error. I create a `.sregistry` at `$HOME` with `"NAME"` and `"SECRET_KEY"` keys. I'm not sure if this is Ok, I don't read anywhere how to build this file.

But then when trying to call to `sregistry push` command I get:
```
TypeError: inspect() got an unexpected keyword argument 'deffile'
```

I'm completely lost.

Thanks,
Víctor

**Comment by vsoch** [comment]
You are totally right! I had another file written and complete forgot to add it. Here it is, with complete instructions!

https://singularityhub.github.io/sregistry/credentials.html

The inspect is a bug too I think - give me a few minutes I'll fix it up.

**Comment by vsoch** [comment]
okay the inspect bug is fixed! Installing from https://www.github.com/vsoch/singularity-python development branch should do the trick. Let me know if you run into other trouble!

I noticed that for the (current) versions of Singularity the default of the client is to compress the image going up and down, and note that for 2.4 the default type (squashfs) will already be compressed. It doesn't hurt but it's not necessary, so if you want to not decompress in the meantime add `--nocompress` and in the longer term (when all use squashfs) I will make the default upload without decompression.

Let me know if the above works!

**Comment by victorsndvg** [comment]
Perfect! it works for me now. 

I'm able to launch `sregistry` in a private network, push images and see them in the web page. I'm going to play with it now.

I think, but not sure, I've discovered a bug in singularity-python client while calling `sregistry pull`. I'm going to report it now.

Sorry for being so insistent, but I'm really interested in having sregistry working in a project, or at least being able to evaluate it. Do you think is mature enough or is evolving too fast right now?

Thanks for your great work @vsoch , always love your tutorials and explanations! :wink: 
Also love the registry of registries idea. Is the next thing I'm going to test :smiley: 

Closing issue...

BR,
Víctor

**Comment by vsoch** [comment]
No this is totally fantastic! It's exactly this kind of detailed look over that is needed. And it really is a "if you want it, ask for it, and I'll make it so!" sort of deal. I built Singularity Registry so it would be used, critiqued, and updated to fit the larger needs of the community! I am greatly appreciative :)
