### ISSUE TITLE
Push via website or cli are two different things?

### ISSUE THREAD

**Issue by hashkeks** [singularityhub/sregistry#379]
Hello there,

first I want to thank you for this awesome software! 
Me and a partner were working on porting this to Kubernetes as a little project and then stumbled across the problem, that images which are uploaded via the website are stored in a different place (sregistry/minio) than images pushed via singularity on the cli (sregistry/minio-images). 
We first thought this would be an error in our (unpolished) Kubernetes port, but we also noticed this behaviour with the docker-compose version. 
One can download both images via the website but when one tries to pull the web-uploaded image via singularity cli, this error message occurs: 
```
FATAL:   While pulling library image: error fetching image: unable to download image: error downloading image: requested image was not found in the library
```
We guess that's due to minio not being aware of the other image location sregistry/minio. Is this normal/known behaviour or do we maybe have missed something in the documentation or setup?

All the best

**Comment by vladdoster** [comment]
@hashkeks Could you share the command your'e attempting to run?

**Comment by hashkeks** [comment]
Hey @vladdoster , thank you for your super fast response.
Sure, please see the two attached screenshots that show the commands, error messages and what our collection looks like online. We cleaned the cache and locally saved images inbetween the commands so we can demonstrate it in a clean way :)

cli-push is the image we pushed via cli, web-push is the image we uploaded via the web-gui into the collection. They're actually the exact same images, just named differently.

![gitIssue1](https://user-images.githubusercontent.com/34633191/140530847-fef77c82-b76e-431d-80e7-2af9fef95bd7.jpg)
![gitIssue2](https://user-images.githubusercontent.com/34633191/140530893-31c0f205-bcef-47f8-a2fe-4948133774f6.jpg)

**Comment by vsoch** [comment]
The "upload via web" functionality is fairly deprecated - I really should have removed it. The primary avenue for push/pull should really be the singularity client. I'd be open to either just removing it, or if someone wants to look into consolidating the two actions that would work too.

**Comment by hashkeks** [comment]
Alright then, thanks a lot for clarifying this issue @vsoch !
We actually don't plan to use the web-upload, but stumbled upon this in our tests.
Gonna close this issue then.
