### ISSUE TITLE
docker-compose not working with current version

### ISSUE THREAD

**Issue by loz-hurst** [singularityhub/sregistry#392]
**Describe the bug**

Unable to start sregistry with the `master` branch's docker-compose.yml (fresh checkout, using directions in docs).

**To Reproduce**

Following the directions in the docs to deploy a test docker instance, after configuring and successfully building with `docker build -t quay.io/vanessa/sregistry .` `docker-compose up` fails with:

```
$ docker-compose up
(root) Additional property db is not allowed
```

`docker-compose build` also fails with the same error:

```
$ docker-compose build
(root) Additional property db is not allowed
```

**Expected behavior**

Containers are created and started by docker-compose.

**If applicable, add versions and screenshots to help explain your problem.**

```
$ docker --version
Docker version 20.10.12, build e91ed57
```

```
$ docker-compose version
Docker Compose version v2.2.3
```

This is a fresh Docker Desktop install, these are the versions it came with.

I presume docker-compose.yml is supposed to be a version 1 definitiion (`version` was not required in version 1 was in version 2 but has now been deprecated), which is now deprecated according to Docker: "Version 1 (Deprecated)" (<https://docs.docker.com/compose/compose-file/compose-versioning/>).  I wonder if it needs updating to a newer standard?

**Comment by vsoch** [comment]
It might be time to update then! And it's a bit annoying the newer versions don't support legacy files. Would you care to do a pull request with updates?

**Comment by loz-hurst** [comment]
Sure, it seems to be a simple as putting the existing docker-compose config under a `services` key in the yaml file.  At least the command succeeded after I had done that - I'm not docker expert so there might be more tidying required in the future but at least that gets it running....

**Comment by loz-hurst** [comment]
Just FYI, I'm also getting a deprecation warning from the minio container but it's not fatal:

```
sregistry-minio-1      | WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
sregistry-minio-1      |          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
```

**Comment by vsoch** [comment]
That should be fairly easy to update.

**Comment by vsoch** [comment]
Just a quick question - how did you install docker-compose? I just followed the instructions on the docker site for linux, and I got:

```bash
$ ./docker-compose-Linux-x86_64 --version
docker-compose version 1.29.2, build 5becea4c
```
So I'm wondering if it wouldn't be best to globally update all recipes, perhaps we should put them in a separate folder and add instructions to the docs for how to use given above a certain version?

**Comment by vsoch** [comment]
If you want me to do these changes (and push to your branch here) let me know - I can also fix the issue with the minio envars. I can't do it during the day but could do it during the evening.

**Comment by cpeel** [comment]
https://github.com/singularityhub/sregistry/pull/405 was merged, we should be able to close this issue.
