### ISSUE TITLE
Usage info strings not well formed

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#40]
Hi all,

I'm accessing to usage section of the sregistry web service and I get the following page:
![sregistry_usage](https://user-images.githubusercontent.com/6474985/31432744-9b00a7a8-ae77-11e7-99a2-141e59084226.png)

Here you can see the following help:
```
sregistry pull victorsndvg/hello-world/master
sregistry pull victorsndvg/hello-world/master --name customname.img
singularity pull shub://10.38.3.117/victorsndvg/hello-world/master
singularity pull --name customname.img shub://10.38.3.117/victorsndvg/hello-world/master
```

I think the tag must be concatenated after a colon instead a slash. I'm right?

Like this:
```
sregistry pull victorsndvg/hello-world:master
sregistry pull victorsndvg/hello-world:master --name customname.img
singularity pull shub://10.38.3.117/victorsndvg/hello-world:master
singularity pull --name customname.img shub://10.38.3.117/victorsndvg/hello-world:master
```

BR,
Víctor.

**Comment by vsoch** [comment]
Yes good catch! That is indeed wrong. I just pushed a fix, and added an example for the build (in 2.4) command. Take a look and let me know if I messed anything up.

**Comment by victorsndvg** [comment]
Perfect, thanks!

closing...
