### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by imerelli** [singularityhub/sregistry#402]
Hi, I'm trying to install sregistry to manage my singularity images.
I'm using centos 7 and Docker version 20.10.17, build 100c701
(which is the actual default from the docked repository).
As you probably know docker compose is now part of docker.

I have this error

docker compose up -d
(root) Additional property db is not allowed

which I guess is due to some incompatibility of docker
compose file with my version of docker/docker compose. 

Can you help me in solving this problem?
Is an update scheduled to new versions of docker?
Are there new tools I can use to manage singularity images instead of this?

Thanks

**Comment by vsoch** [comment]
We probably just need to update the compose file for the current version! It looks like all of the current top level images should be moved under services, with possibly a version too,eg.,https://docs.docker.com/compose/compose-file/

If you want to try that I can make suggestions, and when we stumble on something working can do a PR!

**Comment by imerelli** [comment]
I'm not an expert of docker compose... 
if you can update the installation files etc etc
I would be more than happy to test the new installation procedure.

**Comment by vsoch** [comment]
you don't need to be an expert! It's literally just yaml, and one level of nesting. Here is the example they have:

![image](https://user-images.githubusercontent.com/814322/188977341-fcd3bf8b-cb5f-45e6-9693-c34d81203cc8.png)

The only missing piece for the files here is the top level "services" to wrap what we already have.

**Comment by imerelli** [comment]
As suggested, I was able to install sregistry just modifying the docker-compose.yaml file by placing everything under the "services:" top level tag.

**Comment by vsoch** [comment]
woohoo! If you'd like to pull request with these changes (in the root docker-compose.yaml and the one in the https folder) it would be hugely appreciated. If not, I can make the same changes and ask for a quick review. 

And see - you totally rocked it!

**Comment by vsoch** [comment]
This will be closed by https://github.com/singularityhub/sregistry/pull/405 where I've updated instructions (docs) and the docker-compse.yml recipes.

**Comment by cpeel** [comment]
https://github.com/singularityhub/sregistry/pull/405 was merged, we should be able to close this issue.
