### ISSUE TITLE
tools/template-registry.md does not exist

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#42]
Hi,

I'm trying to follow the registration process here https://singularityhub.github.io/sregistry/setup.html, but it seems that  `template-registry.md` does not exist anywhere.

See https://github.com/singularityhub/sregistry/blob/master/shub/apps/base/management/commands/register.py#L57

Please, Let me know how to proceed! 

Thanks

**Comment by vsoch** [comment]
hey @victorsndvg ! The template file is referenced from a template folder (a django normal thing to do) so you would want to run the command to generate your template:

```
$ python manage.py register

Registry template written to taco-registry.md!

Your robot is at https://vsoch.github.io/robots/assets/img/robots/robot10626.png
1. Fork and clone https://www.github.com/singularityhub/sregistry
2. Add taco-registry.md to the registries folder
3. Download your robot (or add custom institution image) under assets/img/[custom/robots]
4. Submit a PR to validate your registry.
```
I'm in `/code` inside the image, and my `taco-registry.md` is produced here.
```
$ ls
AUTHORS.md	 building-sregistry.json  manage.py	    shub
CONTRIBUTING.md  celerybeat-schedule.db   nginx.conf	    shub.wsgi
Dockerfile	 docker-compose.yml	  paper		    static
LICENSE		 docs			  requirements.txt  taco-registry.md
README.md	 https			  run_uwsgi.sh	    uwsgi.ini
Singularity	 images			  scripts	    uwsgi_params.par
```

And here is the content
```
$ cat taco-registry.md 
---
layout: registry
title:  "Tacosaurus Computing Center"
base: http://127.0.0.1
date:   2017-10-13 07:21:34
author: vsochat
categories:
- registry
img: robots/robot10626.png
thumb: robots/robot10626.png # wget https://vsoch.github.io/robots/assets/img/robots/robot15570.png
tagged: taco
institution: Tacosaurus Computing Center
---

Tacosaurus Computing Center is a Singularity Registry to provide institution level Singularity containers.
```

Did you try that and are having trouble?

**Comment by vsoch** [comment]
oh derp, it wasn't added to the repo! I just added it. Apologies for the oversight!

https://github.com/singularityhub/sregistry/blob/master/shub/apps/main/templates/tools/template-registry.md

The command should work now.

**Comment by victorsndvg** [comment]
Yes, I tried and is easy to create it by hand. But better to have the template :laughing: !

Thanks!
