### ISSUE TITLE
PLUGINS_ENABLED cannot be set in the settings.yaml file.

### ISSUE THREAD

**Issue by karcaw** [singularityhub/sregistry#431]
the PLUGINS_ENABLED parameter can only be set in the environment, and not the settings.yaml file.  I also suspect the secrets.py file will also be ignored.

https://github.com/singularityhub/sregistry/blob/ee23901a00a23d0d2a65fab5f484c803cfd60e44/shub/settings.py#L441

**Comment by vsoch** [comment]
Those would come from a comma delimited list `SREGISTRY_PLUGINS_ENABLED` in the environment. https://github.com/singularityhub/sregistry/blob/ee23901a00a23d0d2a65fab5f484c803cfd60e44/shub/settings.py#L451
