### ISSUE TITLE
NGINX Manifest unkown

### ISSUE THREAD

**Issue by huppfi** [singularityhub/sregistry#440]
Hey, 

I don't know if I am being dumb but everytime I try to docker-compuse up -d it can't pull the ghcr.io/singularityhub/sregistry_nginx:latest. 

What am I doing wrong?

**Comment by vsoch** [comment]
The packages are on quay.io and not ghcr.io.

**Comment by huppfi** [comment]
So I need to change all the ghcr.io mentions in the docker-compose.yml to quay.io?

**Comment by vsoch** [comment]
Looks like they should be there and the build failed, actually - I missed it. https://github.com/singularityhub/sregistry/actions/runs/4824831532

**Comment by huppfi** [comment]
Ah ok so I just need to wait for the build to succeed? Because I don't seem to have permissions for quay.io and I also don't have a redhat account.

**Comment by vsoch** [comment]
I'm giving it another go - I should be able to see the issue this time! You wouldn't want to use an older container anyway.

**Comment by huppfi** [comment]
Thank you!

**Comment by vsoch** [comment]
okay the images are there! https://github.com/orgs/singularityhub/packages?repo_name=sregistry Honestly I don't know what happened the first time - probably some ephemeral GitHub issue. I need to go to bed (almost 3am) so I can't help more tonight, but please open another issue if you run into trouble. Thanks!

**Comment by huppfi** [comment]
Incredible thank you for the quick work!
