### ISSUE TITLE
SRegistry & GitLab. Build service

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#45]
Hi all,

I think how Singularity-hub works together with GitHub is really great and easy for end-users.

As GitLab is the "community GitHub clone", I think it could be interesting to provide a bridge to connect local installations of SRegistry and GitLab. This brings the power to custom site administrators to provide fast/easy building of Singularity containers.

What do you think?

**Comment by vsoch** [comment]
I think this is already done, you just need to enable it :)

https://github.com/singularityhub/sregistry/blob/master/shub/settings/config.py#L36

Do you mean connect for triggering builds?

**Comment by victorsndvg** [comment]
Sorry for the poor/naive explanation.

Yes, I mean connect for building in a CI cycle. Like with the `Singularity` file in GitHub repositories.

**Comment by vsoch** [comment]
Well, since Singularity Registry doesn't rely on Github / any kind of build hook, I don't see any reason that you couldn't have a build and then push from a CI cycle. Did you have something different in mind? Remember that sregistry doesn't offer building as a service - it puts you in charge of building (and you build as you like and then push). Let me know what you had in mind!

**Comment by victorsndvg** [comment]
Mmmm yeah, you'r right ... I will play from the GitLab side to integrate a singularity image building into the CI.

Just brainstorming ... I will reopen the issue If I have something new in mind.

Thnks!

**Comment by victorsndvg** [comment]
Hi,

Again with this issue.

We are hosting a Gitlab service and providing CI based on it. We would like to provide a service to automatically push Singularity containers to our own SRegistry (probably via webhooks?).

Is there any public tool for that?

If not, which tools you recommend to use?

Maybe this approach is wrong ... any suggestion?

Thanks in advance!

**Comment by vsoch** [comment]
Can't you just push with sregistry? Why is a webhook needed?

**Comment by victorsndvg** [comment]
Hi @vsoch ,

Yes we can build Singularity containers from Gitlab-CI and also use `sregistry`  command to push these images to our SRegistry. This use case means that the Gitlab users has direct access to SRegistry service and they know their secret.

We are exploring other alternative use cases. One of them is to use the SRegistry service in "background" and hidden to the end-user. This means that an "intermediate admin" will be in charge of managing (at least) the credentials. In this case an intermediate service needs to interact between GitLab-CI and SRegistry to: (1) clone the repo, (2) build the container, (3) push to sregistry.

Do you think this alternative use case is a non-sense?

**Comment by vsoch** [comment]
I think that sounds really cool, but a specific Builder and continuous integration service it's outside of the scope of Singularity registry.

**Comment by victorsndvg** [comment]
Yeah, sorry, I completely agree with you.

Probably the issues system is not the right place to ask for this. I didn't intent to get the work done by SRegistry, but as you are more experienced than me in these technologies, I would like to know your suggestion about which technologies I can use ...

Maybe django, celery, etc.

Thank you and sorry for the misunderstanding

**Comment by vsoch** [comment]
hey if you are interested I'd add this to our "larger thinking about the future" sregistry project. Right now it's focused on adding Globus (and better capturing metadata, etc.) but a build system is going to be something we think about.
