### ISSUE TITLE
Return status 403 Unauthorized on push

### ISSUE THREAD

**Issue by sysmso** [singularityhub/sregistry#46]
Hi,

I've setup a local sregistry, and add my user as superuser and admin. I've copy-paste the token from gui, then put in my home .sregistry, then do a push : 

`sregistry push openmpi.img --name openmpi
[================================] 196/196 MB - 00:00:0096 MB - 00:00:00
Upload finished! [Return status 403 Unauthorized]
`
`sregistry list
No container collections found.
`
How can i debug this ?
Thanks

Martin

**Comment by vsoch** [comment]
Did you copy the entire jason object with the token, and is it where your variable $HOME is as a hidden file? (note the dot before it)

**Comment by vsoch** [comment]
It's definitely an auth issue - you are hitting this if statement:
```
        if not validate_request(auth,payload,"push",timestamp):
            raise PermissionDenied(detail="Unauthorized")
```

if you want to try:

```
docker-compose logs uwsgi
```
that might give you some additional output on the server to see

**Comment by sysmso** [comment]
Push with debug : 
`sregistry --debug push openmpi.img --name openmpi
DEBUG Headers found: Content-Type
DEBUG PUSH /home/ssysmso/git/tp-singularity/openmpi.img
DEBUG openmpi.img was built from a definition file.
[================================] 196/196 MB - 00:00:0096 MB - 00:00:00
Upload finished! [Return status 403 Unauthorized]
`
` ls -l ~/.sregistry 
-rw-r--r-- 1 ssysmso ssysmso 115 17 oct.  15:40 /home/ssysmso/.sregistry`

On the server, docker logs show : 
`DEBUG push/Z2V0Y2hhYWE=/20171017T15Z
DEBUG 20171017T15Z is expired, must be 20171017T17Z.
[pid: 53|app: 0|req: 10/10] 134.158.186.89 () {40 vars in 768 bytes} [Tue Oct 17 12:26:39 2017] POST /api/push/ => generated 25 bytes in 978 msecs (HTTP/1.1 403) 5 headers in 162 bytes (4 switches on core 0)
`

**Comment by vsoch** [comment]
ahh it's a timezone bug! Let's look at the differences between generating the timestamps, and then I'm not actually sure what the difference between `5Z` and `7Z` is!

**Comment by vsoch** [comment]
okay, so Singularity Registry is using UTC:

```
def generate_timestamp():
    return datetime.utcnow().strftime('%Y%m%dT%HZ')
```

and the sregistry command line tool us using:

```
def generate_timestamp():
    return datetime.datetime.utcnow().strftime('%Y%m%dT%HZ')
```
the same thing (just different import)

**Comment by vsoch** [comment]
And the `%H` means the hour, so the difference in 5 and 7 would indicate 2 hours off between what the local call and server is producing. Is this on your local machine?

**Comment by vsoch** [comment]
I think the naive datetime is probably using some setting from your OS (different from the server). Let me try making it non-naive and setting a timezone.

**Comment by vsoch** [comment]
okay I just updated the timezone functions to do this:

```
def generate_timestamp():
    ts = datetime.now()
    ts = ts.replace(tzinfo=timezone.utc)
    return ts.strftime('%Y%m%dT%HZ')
```

Could you please test now? You would need to reinstall singularity-python and pull and `docker-compose restart` for sregistry. If this still doesn't work, then let's try a:

```
docker-compose iit <image_id> bash   # "interactive terminal bash"
```
and then go into python in the image, test the function, and compare with the output on your local machine. We would want to find a consistent method for returning the same (non naive) timestamp regardless of underlying OS, etc. Your help is greatly appreciated!

**Comment by sysmso** [comment]
Okay it's working fine now. Thank you !

**Comment by vsoch** [comment]
:)

**Comment by sysmso** [comment]
Sorry to reopen this issue, but I have an error with the new version of sregistry which seems very close to this issue : 

[ssysmso@apcnb170 singularity]$ sregistry push multinest.img --name library/pymultinest --tag python
[================================] 403/403 MB - 00:00:00
[Return status 403 Unauthorized]

Docker logs : 
DEBUG push/Z2V0Y2hhYWE=/20171214T18Z
14/12/2017 20:07:45 DEBUG 20171214T18Z is expired, must be 20171214T19Z.

Have you an idea or should i open a new issue ?

Thanks

**Comment by vsoch** [comment]
Are you installing sregistry locally or via the provided Singularity file?

I don't think anything has changed so I'm not sure how to debug this.

**Comment by sysmso** [comment]
Locally via github.

**Comment by vsoch** [comment]
I think what we probably need to do is to separate out the modules so sregistry client is separate from the rest of singularity hub / builder tools, which have a bunch of dependencies that keep causing these errors. In the meantime can you use a previous commit?

**Comment by vsoch** [comment]
you will be first up to test it @sysmso ! Give me some time to develop this, and I'll ping you when it's ready. :)

**Comment by vsoch** [comment]
oh, I think this is an easy fix. Are you using python2 ? You must use 3, it's even in the README. You can either install with python 3, or use the provided container that has it.

**Comment by sysmso** [comment]
I'm using python 3.

**Comment by vsoch** [comment]
okay I promise to work on this soon for you. Could you give the exact sequence of install and run commands so I can reproduce the result, and use `which` to show versions, locations?

**Comment by sysmso** [comment]
[ssysmso@apcnb170 singularity-python]$ git status
On branch development
Your branch is up to date with 'origin/development'.
[ssysmso@apcnb170 singularity-python]$ sudo python3 setup.py install
[...]
Using /usr/lib/python3.6/site-packages
Finished processing dependencies for singularity==2.4.1
[ssysmso@apcnb170 singularity]$ sregistry --version
2.4.1
[ssysmso@apcnb170 singularity]$ which sregistry
/usr/sbin/sregistry
[ssysmso@apcnb170 singularity]$ sregistry push multinest.img --name library/pymultinest --tag python
[================================] 403/403 MB - 00:00:00
[Return status 403 Unauthorized]

Do you need other informations ?

**Comment by vsoch** [comment]
Did you try from master? Development was merged a bit back.

**Comment by vsoch** [comment]
And did you make sure your token is still good in the file `$HOME/sregistry`

**Comment by sysmso** [comment]
From master, same error : 
[ssysmso@apcnb170 singularity]$ sregistry --debug push multinest.img --name library/pymultinest --tag python
[================================] 403/403 MB - 00:00:01
Upload finished! [Return status 403 Unauthorized]

The token is good, i can pull and list.

**Comment by vsoch** [comment]
hey @sysmso ! I've gotten a chunk of work done with the updated version of the client for sregistry - and actually it is going to be a nice interface for push/pull of singularity images from multiple different places (right now just a singularity registry and singularity hub). The code lives in [this repo](https://github.com/singularityhub/sregistry-cli)  and how I've been (early testing!) it is [here](https://github.com/singularityhub/sregistry-cli/blob/master/examples/client/run_client.sh)

and they aren't done yet, but I'm working on containers to run them.  After you install (please use python 3) It works by determining the client to use based on what you've set in the environment, so for a singularity registry you would want to export `SREGISTRY_CLIENT_SECRETS` and just leave empty/undefined to use Singularity Hub as the endpoint type.

```
git clone https://github.com/singularityhub/sregistry-cli
cd sregistry-cli && python3 setup.py install
export SREGISTRY_CLIENT_SECRETS=$HOME/.sregistry
sregistry push vsoch-hello-world-latest.simg --name tacos/tacos
```
I'd be interested in your feedback on what kinds of "storage places" would be useful for you! If you want to pick up this issue there feel free to open there and close here, I'm planning on (when the client is shiny and ready) to deprecate it's use in the singularity python repository.

**Comment by sysmso** [comment]
Hello !
I have the same problem with this new client : 
sregistry --debug push multinest.img --name pymultinest
[================================] 403/403 MB - 00:00:00
[Return status 403 Unauthorized]

DEBUG push/Z2V0Y2hhYWE=/20171218T09Z
18/12/2017 11:31:24DEBUG 20171218T09Z is expired, must be 20171218T10Z.

I think it's due to the different time on the client and the server. 
The singularity registry is a good storage place for our needs, no need for other storages places at this point.

**Comment by vsoch** [comment]
Both times should be UTC, so do you think the actual sync of the minutes is off? I ran into this issue when I had a different function on the registry calculating the time than the sregstry software, and doubly the pip uninstall didn't remove the old executable (and so I was using the old one). That would be another thing to check! If not, then I would want to ask for some way to reproduce this. Ty!

**Comment by sysmso** [comment]
I force a new sync between server and client and now it's working...
Thank you for your help !

**Comment by vsoch** [comment]
awesome! It's not unheard of also to have a sync that is off - a user just reported this on one of our servers and it made some pretty error messages about time :) Closing issue!
