### ISSUE TITLE
Missed generate_cert.sh referenced in install.md

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#47]
Hi,

I'm getting into troubles to configure sregistry with https. I try to follow your instructions, but `generate_cert.sh` referenced in `install.md` does not exist.

**Comment by vsoch** [comment]
Here you go!

https://github.com/singularityhub/sregistry/blob/master/scripts/generate_cert.sh

I would walk through the steps manually the first time. The dhparam file takes a long time to make, and it's good to see the output of each command that you issue. Note at the top you need your install root and some other infos about the domain for the registrar.

**Comment by victorsndvg** [comment]
Great @vsoch , Thanks again! 

I have checked that `singularity pull` command only works with `https` registries. I'm right?

**Comment by vsoch** [comment]
Nope you can do:

```
SINGULARITY_NOHTTPS=yes singularity pull shub:// ...
```
or just export that variable first.

**Comment by victorsndvg** [comment]
Thanks it works!
