### ISSUE TITLE
relation "users_user" does not exist

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#48]
Hi, 

deploying the entire infrastructure or piece by piece and taking a look to the logs I can see some errors related with `users_user` table (I think).
```
uwsgi_1   | django.db.utils.ProgrammingError: relation "users_user" does not exist
```
```
db_1      | 2017-10-19 11:13:14.396 UTC [63] ERROR:  relation "users_user" does not exist at character 397
db_1      | 2017-10-19 11:13:14.396 UTC [63] STATEMENT:  SELECT "users_user"."id", "users_user"."password", "users_user"."last_login", "users_user"."is_superuser", "users_user"."username", "users_user"."first_name", "users_user"."last_name", "users_user"."email", "users_user"."is_staff", "users_user"."is_active", "users_user"."date_joined", "users_user"."active", "users_user"."admin", "users_user"."agree_terms", "users_user"."agree_terms_date" FROM "users_user" WHERE "users_user"."username" = 'AnonymousUser'
db_1      | 2017-10-19 11:15:31.119 UTC [68] ERROR:  relation "users_user" does not exist at character 397
```

What do you think?

**Comment by vsoch** [comment]
Usually you just need to restart. I am assuming when you update the cod you do docker-compose restart?

**Comment by victorsndvg** [comment]
Yes, I'm getting troubles to have it working with https. Maybe I need to start again from a clean environment. I will tell you if the problem persists.

I would like to test pulling and pushing between 2 different servers. But only `singularity` allows to pull from a remote server. I cannot do it with `sregistry`. `singularity pull` use only https to get images. I'm right?

**Comment by victorsndvg** [comment]
Ok, I saw your response in another thread. lets postpone playing with https.

If in the future the problem persist I will reopen the issue

**Comment by vsoch** [comment]
sregistry would work given you have credentials, and given that you change the host url to something else. Both of those things are in the credential file, so I don't see any reason that you couldn't push to two different ones as long as the right credential is used.

**Comment by victorsndvg** [comment]
`push'?? I don't know how to specify a different host to push. Is it possible?

With `pull` I get the following error:
```
$ sregistry --debug pull shub://10.38.3.35/dinosaur/avocado:whatinthe
DEBUG Headers found: Content-Type
DEBUG Execution of PULL for 1 images
DEBUG Retrieving manifest at http://10.38.3.235/api/container/shub://10.38.3.35/dinosaur/avocado:whatinthe
DEBUG GET http://10.38.3.235/api/container/shub://10.38.3.35/dinosaur/avocado:whatinthe
DEBUG {}
Traceback (most recent call last):
  File "/usr/local/bin/sregistry", line 9, in <module>
    load_entry_point('singularity==1.2.0', 'console_scripts', 'sregistry')()
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/__init__.py", line 208, in main
    subparser=subparsers[args.command])
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/main/pull.py", line 38, in main
    decompress=not args.nodecompress)
  File "/usr/local/lib/python2.7/dist-packages/singularity-1.2.0-py2.7.egg/singularity/registry/client/pull.py", line 63, in pull
    image_file = self.download(url=manifest['image'],
KeyError: 'image'
```

**Comment by vsoch** [comment]
Did you go to the url and verify that "image" is in the manifest? It could be that it is the wrong url (and returning a no detail page) or that the image somehow didn't fail to be pushed and doesn't have an image.

Yes, the main point of sregistry is that the admin can push images to it, for example:

https://singularityhub.github.io/sregistry/client.html#push

The way that works is by finding the credentials file `.sregistry` at your home, OR finding a custom path at `SREGISTRY_CLIENT_SECRETS`:

https://github.com/vsoch/singularity-python/blob/development/singularity/registry/auth.py#L85

So If you have two hosts, that corresponds with two credentials file, and you can just change your environment variable to be the one that you want active for the push:

```
SREGISTRY_CLIENT_SECRETS=/path/to/.sregistry-secrets-host1 sregistry push ....
SREGISTRY_CLIENT_SECRETS=/path/to/.sregistry-secrets-host2 sregistry push ....
```

**Comment by victorsndvg** [comment]
Aahh ... eureka! :laughing: 

I thought `singularity-python` should be installed on the same host that `sregistry`, and the secrets work only with the "local" registry. Now I understand perfectly ... and I love it! haha

Thanks again and sorry for misunderstanding everything ...
