### ISSUE TITLE
HELP_INSTITUTION_SITE prepends SRegistry URL

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#53]
Hi,

I don't know if this is the expected behaviour, but `HELP_INSTITUTION_SITE`, defined in this [line](https://github.com/singularityhub/sregistry/blob/9276e648f3b9539ea435bc09ed722522f68b048c/shub/settings/config.py#L54), prepends the SRegistry URL (E.g. localhost IP address) in the `Request a build` section of the main page of the SRegistry.

I think, at least in my case, it is more general to allow to link external web sites.

What do you think?

**Comment by vsoch** [comment]
hey @victorsndvg ! I think you likely just need to add http or https? if you look at how the variable is used:

```
<li><a href="{{ HELP_INSTITUTION_SITE }}"><i class="fa fa-home"></i></a></li>
```
This would mean that whatever you define there will be linked to. It would only pre pend the sregistry url if you don't give http or https.

**Comment by victorsndvg** [comment]
Yes @vsoch ,

You are right, I thought I manually change `config.py` ... but I was wrong. 

It works as expected. Prepending `http` to the URL in `HELP_INSTITUTION_SITE` points to the right URL from the main website page.

Thanks ...  and sorry!

Closing ..

**Comment by vsoch** [comment]
haha no worries! :)
