### ISSUE TITLE
Registary mirror

### ISSUE THREAD

**Issue by HelenCousins** [singularityhub/sregistry#54]
With docker it is possible to run a local registry as a proxy cache  we would like to have something similar for singularity, is this currently possible?  (we mostly want to keep the internet traffic down when someone starts 1000 jobs  which all start by pulling the same image).  As a similar issue we'd quite like to run a local registry, but I can't see how to configure sregistry for purely local use.

**Comment by vsoch** [comment]
hey @HelenCousins could you give me more information about what a proxy cache is / does /works? I can then better answer the first question.

For the second, ideally a run of 1000 jobs would start with a slight offset so the pull is done with the first, and then the others find the image in the cache (note that all commands to use an image check the cache first). You would want to make sure that the user is pulling to his/her cache or some shared cache and not the present working directory (which it will default to if the environment variables for `SINGULARITY_PULLFOLDER` and `SINGULARITY_CACHEDIR` are not set.  Overall for this runtime issues I'm thinking this is more on the job manager / submission script side (responsibility wise) than sregistry, but it's important so I think we could come up with some docs and examples of how to do this using various architecture. 

For local use, do you mean to say only accessible to your local cluster? You can control this in a few ways. The first is having an institution based login that ensures that outside folk don't log in, and this would mean still having a (world) web accessible registry although they can't do much but look at the home page. You can also easily deploy it on a server that is behind your institution firewall, and I think likely this makes most sense (@dctrud is this akin to how you deployed the private one?) I would again say that the customization of the privacy is going to vary by institution, and one preference shouldn't be "hard coded" into the settings, but we **should** provide examples for how to go about this.

**Comment by HelenCousins** [comment]
What the cache does is you do docker pull and the 1st time it gets it from dockerhub but the next many times it has it locally.  It has cache expiry magic too.  (incidentally I understand singularity can get from docker hub, can it get from our local docker registry?)

I think we want to run it inside our firewall, partly because 'bandwidth' and partly because we might have some data protection type issues (I'm unsure, I don't do the science just the IT...).  Having to fiddle the settings is fine, but some documentation that says how would be great.

**Comment by vsoch** [comment]
The cache then should be handled already by singularity - pulling a registry image uses the same pull command for singularity (proper), and then it won't try to pull from the endpoint if it finds it locally.  Singularity doesn't have "cache expiry magic," you would just need to purge it every so often. The default is at a user's `$HOME/.singularity` with subfolders for docker and shub (also registry) respectively.

@dctrud can you comment on running behind firewall? I don't have experience setting it up in this fashion.

**Comment by dctrud** [comment]
@vsoch - I think what @HelenCousins wants is a solution that would provide caching for all users. If I pull then it's cached in my $HOME, but if 80 other people pull it then there is no caching for them. That could be an issue for places with very constrained bandwidth and many users pulling the same large image.

@HelenCousins - when you say configuring solely for local use, are you referring to authentication using local accounts? The setup here is that the sregistry can be 1) behind the institution firewall (so nobody outside can even reach it. 2) Setup so that LDAP auth against our local LDAP server is the only enabled auth method (no twitter etc).

**Comment by vsoch** [comment]
Thanks @dctrud ! For caching, would it be unreasonable to set a (global / cluster wide) environment variable for `SINGULARITY_PULLFOLDER` ? It could be loaded when the user loads a singularity module, for example. They would have to over-ride it to make a different pull folder.

**Comment by dctrud** [comment]
@vsoch - could be reasonable, but assumes sane locking and permissions setup for mutliple users coming at it from different places. How would singularity behave if someone else tries to pull a layer, whilst the first user is halfway through pulling it?

**Comment by vsoch** [comment]
If the first user is halfway through pulling it, it's setup with some concurrency so that while it's not yet complete it is downloaded with a temporary extension, and only renamed when complete. Then the final (complete file that was renamed) is found by the other processes that need it. This is why I suggested to @HelenCousins that given that some knowledge that a container is going to be used 1000 times at exactly the same time, a single job is run first with some lag before to download the image.  This example is no different than what happens when a single user on a cluster runs 1000s of jobs that use the same image. If there is some additional functionality or control here, it should be resolved with the Singularity software proper. The registry itself is just a http endpoint that knows how to serve an image when it's requested for download, and the driver is Singularity proper deciding how to control that.

**Comment by dctrud** [comment]
@vsoch - yes, sorry, my comment probably sounds off. When talking about sane locking etc I wasn't thinking about Singularity not doing sensible things, but more thinking about parallel file systems where node-local or no locking is common. Plus permissions if e.g. someone has a restrictive umask set then they'd could create files not readable to others within the comon PULLFOLDER. ACLs on the PULLFOLDER could offer a way around this.

**Comment by HelenCousins** [comment]
I think we could usefully use a shared folder, that would make sense (especially as people are very particular about version consistency).  But we'd sort of llike  local registry to do the 'build my image' stuff.

**Comment by vsoch** [comment]
hey @HelenCousins , Singularity Registry assumes the institution / user has a build environment (CI in a github repo, local node, computer, etc) and so doesn't provide this service. The hard part about adding that is the fact that there are infinite numbers of ways / preferences /variables that an installation might warrant, so the general command to push (a finished image) to the registry is a reasonable approach.  Could you tell me about your use case so I can make suggestions?

**Comment by HelenCousins** [comment]
I want to do 
singularity pull MYSERVER://my/image
and also push to it (the CI can be added later) as a place to store local images to save on bandwidth and avoid any possible data protection issues.  

I also want to do
singularity pull my-insecure-docker-registry://my/image
which it appears I can't do out of the box. (we have a local docker registry and also make heavy use of quay.io

**Comment by vsoch** [comment]
>> I want to do
>> singularity pull MYSERVER://my/image

You should be able to pull a singularity image from your registry. If you want a shared cache, then set a `SINGULARITY_PULLFOLDER` exported for everyone and it will not re-download images

>> and also push to it (the CI can be added later) as a place to store local images to save on bandwidth and avoid any possible data protection issues.

You can push too, but not with the singularity client, with sregistry. Assuming you have downloaded your token file and it's located at `$HOME/.sregistry`

```
sregistry push --name namespace/container container.simg
```

>> I also want to do
>> singularity pull my-insecure-docker-registry://my/image
>> which it appears I can't do out of the box. (we have a local docker registry and also make heavy use >> of quay.io

this is not an issue to post here, but with singularity. https://github.com/singularityware/singularity/issues

**Comment by vsoch** [comment]
@HelenCousins this should be handled (not via some official mirror) but by way of Singularity using a cache. Push and pull have also both been added.
