### ISSUE TITLE
Return status 403  with sucessfull exit code

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#56]
Hi,

I have a frozen image stored in SRegistry, I try to overwrite this image and SRegistry works as expected. Nothing change on SRegistry side:
```
$ sregistry push --name alpine/container --tag 3.6 alpine.3.6.simg

Upload finished! [Return status 403 alpine/container:3.6 is frozen, push not allowed.]
```
But `sregistry` command return a successful exit code. 

Do you think this is the right behaviour?
It could be possible to return an error code in this case?

Let me know your thoughts!

**Comment by vsoch** [comment]
The upload finished is just misleading, it prints that when the upload process is finished. The upload DOES happen but it's not actually saved in sregistry. I agree a better message is needed!

**Comment by vsoch** [comment]
hey @victorsndvg I just pushed a fix to development that removes the misleading message - it's probably not dire so you don't need to update your base, but FYI it will be resolved for next release!  https://github.com/singularityware/singularity-python/issues/84

**Comment by victorsndvg** [comment]
Ok, thanks @vsoch , now I understand how it works. great work! :+1
