### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by iliaboti** [singularityhub/sregistry#62]
Hello, 

I am following the guide at https://singularityhub.github.io/sregistry/plugins/ldap.html in order to integrate a "User registry" with LDAP running on an active directory.

The process tops at the point there I post to: Request URL:http://host.com/ldap_auth/login/?next=http://host.com/login/ the data 

csrfmiddlewaretoken:long_token_here
username:username
password:password

The result is a 500 Internal Server Error code. But the log file shows only that and nothing more to make me understand what could be the issue. 

uwsgi_1 | [pid: 59|app: 0|req: 11/11] xxx.xxx.xxx.xxx. () {50 vars in 2650 bytes} [Mon Dec  4 10:40:57 2017] POST /ldap_auth/login/?next=http://host.com/login/ => generated 850 bytes in 19 msecs (HTTP/1.1 500) 4 headers in 142 bytes (1 switches on core 0)

Is it possible to understand where the problem might be and more importantly how to get more debugging information ? 

Best regards,
Ioannis

**Comment by vsoch** [comment]
I don't have much experience with LDAP so @dctrud might need to step in and help! With these authentication flows it usually is the case that a request or response is formatted in an unexpected way, an the server 500s. The most obvious things to check would be what they always are - paths, and if your server requires a certificate, etc.

To debug, I think there are two ways I can think of for going about it. The first sanity check would be that your LDAP setup is working as expected. For you this probably is already done and known, for me what I had to do is use a Docker container to test a dummy one --> https://singularityhub.github.io/sregistry/plugins/ldap.html#create-the-server

Then I would look over the docs for the underlying module that is being used --> https://django-auth-ldap.readthedocs.io/en/1.2.x/authentication.html You might read that and see that there is some special config that is needed for your server, and then add it (and if you find this to be the case, we can add a note to the docs so others can find it in the future). From what @dctrud has told me, all of these LDAP servers are snowflakes, and I suspect this kind of issue is likely.

Then probably a good strategy is to walk through the function so you can trigger the error in a console, and work with the code from within the sregistry container.  The codebase I think is from bitbucket --> https://bitbucket.org/illocution/django-auth-ldap/src/84af541661fe06d686ddc7bc2f41ebe26ef0739a?at=default I'm surprised there isn't more information about the error beyond a server error, if I remember correctly the ldap is configured to have its logging output to the console. @dctrud does that seem like a reasonable start, and do you have any quick thoughts or suggestions?

**Comment by dctrud** [comment]
@iliaboti - Try putting this in with your LDAP config:

```
import logging

logger = logging.getLogger('django_auth_ldap')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)
```

.. to enable DEBUG logging for django_auth_ldap. For AD you might need slightly different LDAP settings. E.g. most AD setups I've seen won't work with anonymous bind - you need to specify bind user and pw. You may also need to disable referrals. Something on the web with some detail is at:

**Comment by vsoch** [comment]
Thanks @dctrud!

**Comment by iliaboti** [comment]
Dear @vsoch , @dctrud ,

Thank you vary much for the hints. However I have discovered the following. 

The Dockerfile has those two lines commented: 

# Install LDAP (uncomment if wanted)
# RUN pip install python3-ldap
# RUN pip install django-auth-ldap

Therefore no ldap authentication was attempted but also no logs where generated for that. I did docker docker exec -it xyz bash and install the two modules. Then it worked really well! 

Maybe this should go somewhere in the documentation if not already there. I might have not noticed it. 

Thanks again,
Ioannis

**Comment by vsoch** [comment]
That would do it (; Here are the missing instructions!

https://singularityhub.github.io/
