### ISSUE TITLE
Weird behaviour depending on the browser.

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#64]
Hi,

I would like to know if it's possible to change the privacy of a collection using th web interface if an admin user is loged-in.

Is it possible?

Thanks!

**Comment by vsoch** [comment]
hey @victorsndvg ! Under the Settings dropdown there should be an "edit" button, and on that page a button to make a collection private or public. If you don't find it, please take some screen shots and tell me the status of the user (manager, admin, both, none)

**Comment by victorsndvg** [comment]
Ops, I can confirm that using Firefox 50.0.2 I cannot see the menus displayed when click on `Supplementary`, `Settings` and `Administration`.

I am also experiencing an issue with Chromium Version 47.0.2526.106. When I push the `Open/Frozen` button it has no effect.

Maybe I'm missing something ...

Which requirements related with browser are involved to have SRegistry working?

Thanks!

**Comment by vsoch** [comment]
I use Chrome, and make sure your ad blockers are disabled. Even things like font awesome icons (common on buttons) are sometimes considered ads depending on your blocker and settings.

**Comment by victorsndvg** [comment]
Hi @vsoch ,

I don't have any extension or complement installed in the browser.

How can I check what is happening?

**Comment by vsoch** [comment]
Please try chrome (not chromium) it's also helpful to right click --> inspect and then look at the "console" tab - sometimes errors / bugs are there. If you still don't see anything, it's likely your user you are logged in the browser doesn't have the right permissions (or the user you are logged in isn't the superuser account you think it is).

**Comment by victorsndvg** [comment]
With Firefox I got 2 warnings:

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[know more]  jquery.min.js:1
Using getPreventDefault() desaproved. Use defaultPrevented instead.  jquery.min.js:5:12747
```
Note: translated by me :thinking: 

It has sense for you? Menus can be failing for this reason?

**Comment by vsoch** [comment]
Chrome... ;)

**Comment by victorsndvg** [comment]
Sorry, chromium is working now. Is firefox the browser is not working properly. no idea about chrome

**Comment by victorsndvg** [comment]
With Firefox, It seems that something is happening with the `class=dropdown-menu`.   Removing it I can see the menu (always) and interact with it

**Comment by vsoch** [comment]
I think fixing firefox is probably outside the scope of an sregistry issue :) https://support.mozilla.org/en-US/questions/1088303

**Comment by victorsndvg** [comment]
Ok, Thanks for your help.

Closing ...

**Comment by vsoch** [comment]
@victorsndvg are you saying that removing the class completely didn't hurt, but resolved the issue?

**Comment by victorsndvg** [comment]
@vsoch , no, it looks ugly, it's not a production solution. But thanks again, we will recommend Chrome and thats all

**Comment by vsoch** [comment]
ok, I'm bringing up the images to take a look anyway.
