### ISSUE TITLE
Allow customization of pull command (and default to pwd)

### ISSUE THREAD

**Issue by sysmso** [singularityhub/sregistry#65]
Hello

When /tmp is on a different partition, you can't have hardlink. I have the problem when I pull a container : 
[ssysmso@apcnb170 singularity]$ sregistry pull library/openmpi:latest
Progress |===================================| 100.0% 
Traceback (most recent call last):
  File "/usr/sbin/sregistry", line 11, in <module>
    load_entry_point('singularity==2.4.1', 'console_scripts', 'sregistry')()
  File "/usr/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/registry/main/__init__.py", line 208, in main
    subparser=subparsers[args.command])
  File "/usr/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/registry/main/pull.py", line 38, in main
    decompress=args.decompress)
  File "/usr/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/registry/client/pull.py", line 65, in pull
    show_progress=True)
  File "/usr/lib/python3.6/site-packages/singularity-2.4.1-py3.6.egg/singularity/hub/__init__.py", line 157, in download
    os.rename(tmp_file, file_name)
OSError: [Errno 18] Invalid cross-device link: '/tmp/library-openmpi-latest.simg.tmp.d64ea0sj' -> 'library-openmpi-latest.simg'

Is it possible to specify another tmp directory ?

Thanks

**Comment by vsoch** [comment]
Hey @sysmso ! There are a few options here. If you use singularity proper, you should be able to pull and then customize the `SINGULARITY_PULLFOLDER` or `SINGULARITY_CACHEDIR` to specify where it is pulled. If you have reason to need to use sregistry to pull, then we could have this be another variable that is "sniffed" from the environment, and I'd be curious to know your thoughts on if this should mirror singularity preferences (e.g., share the variable) or have some other custom `SREGISTRY_PULLFOLDER`. I think the second probably makes sense, in the case that a user wants two different configurations for the two executables. Do you have other ideas for how you would want to set this? A command line argument or similar?

**Comment by vsoch** [comment]
@sysmso those environment variables **dont* work for sregistry, I was asking you about **if** I implemented them.

You can pull from your own registry with singularity, it's like your own singularity hub. You would do:

```
singularity pull shub://localhost/namespace/container
```
If you aren't using HTTPS you need to specify that:


```
SINGULARITY_NOHTTPS=true singularity pull shub://localhost/namespace/container
```

To be clear, here are your choices:
 - use the singularity command to pull, as I've shown above (and modified for your custom registry)
 - clearly indicate your preferences for how sregistry could do it, and then submit a PR to the software or wait until I have time to do the fix.

Thanks!

**Comment by sysmso** [comment]
Sorry I read your answer too fast ! It's ok for me to use singularity command, it works like a charm, thank you !

I think for sregistry that the pull should be done in the current directory and can be modified by environment variables.

**Comment by vsoch** [comment]
okay cool! I will take a look and see what I can do. I'm glad it worked for you! I made the pull only because it was logical to have to match the push, but ideally the optimal way to do it is using singularity (as you normally would).

**Comment by vsoch** [comment]
hey @sysmso ! It turns out that the issue has to do just with the function used to move (rename) the files - the download is done to first go to temporary, and then move to the present working directory when it finishes.  os.rename has the cross device issue (see https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link). It is in fact the case that pull goes to `$PWD` and your case was just erroring out before it was moved (it does this to a temporary location in case there was issue). I updated the client in the branch for this PR - would you like to give it a test?

https://github.com/singularityware/singularity-python/pull/85


Many thanks!

**Comment by sysmso** [comment]
Yes, it's ok for me, I can pull without any problems. Thank you !

**Comment by vsoch** [comment]
awesome! Thanks for the test.

**Comment by vsoch** [comment]
merged into master, closing. Thanks again!
