### ISSUE TITLE
Contributor's Agreement Incompatible with AGPL

### ISSUE THREAD

**Issue by dctrud** [singularityhub/sregistry#68]
Project has been re-licensed to AGPL, which requires source of modified versions must be available to users who can access it it as a public web app.

> The GNU Affero General Public License is designed specifically to ensure that, in such cases, the modified source code becomes available to the community. It requires the operator of a network server to provide the source code of the modified version running there to the users of that server. Therefore, public use of a modified version, on a publicly accessible server, gives the public access to the source code of the modified version.

Contributors agreement states:

> You are under no obligation whatsoever to provide any bug fixes, patches, or upgrades to the features, functionality or performance of the source code ("Enhancements") to anyone;

**Comment by vsoch** [comment]
This was an oversight I forgot to fix up! I will address when we finish discussion on the license itself. Thank you!

**Comment by vsoch** [comment]
I patched this so am closing here, and we can continue discussion in the other thread. Thanks @dctrud !
