### ISSUE TITLE
Data persistent by default

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#74]
It could be interesting to preserve the data by default. This means NOT to store images, databases, etc. inside the containers. 

I think all relevant data should be stored in the host storage by default. This allows non-experienced users to undeploy and restart containers maintaining the data.

I had a `docker-compose.yml` and a data structure in the following fork:
https://github.com/MSO4SC/sregistry

What do you think? is it interesting? I'm missing any data?

**Comment by vsoch** [comment]
hey @victorsndvg I don't totally understand this issue - for Singularity Registry the folders with images, databases, aren't stored in the container (if you look at docker-compose.yml they are mapped to the host) and the admin of course has the choice to use an external database entirely instead of the docker image.

**Comment by victorsndvg** [comment]
Yes, sorry, you are right.

I take the https `docker-compose.yml` file, which is where the image directory binding is missing. I also think the DB container should write by default persistent data to the host, but is up to you, I think is more unexperienced-user-friendly.

Other recommendation, not about persistent data, is to  map the redis port only to localhost. It avoids exposing this port out of the server (i think is insecure) and the creation of undesirable iptables rules

**Comment by vsoch** [comment]
hey @victorsndvg  - the image directory binding to the host does happen in docker-compose - these lines:

```
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
```
say that the folders "static" and "images" in the $PWD (on the host) are bound to /var/www/static and /var/www/images, respectively. You could change those if you like to somewhere else on the host, but this is an individual choice on your part. If you were to shut the registry down, those folders would persist on the host. Am I missing something?

**Comment by vsoch** [comment]
redis is also only relevant to the container running it. See [here](https://github.com/singularityhub/sregistry/blob/master/shub/settings/tasks.py#L42). :+1. The `BROKER_URL` has an address that references the container running redis (known identifier to docker compose):
```
BROKER_URL = 'redis://redis:6379/0'
```
and then the complete celery address includes host, port, and database reference:

```
CELERY_RESULT_BACKEND = 'redis://%s:%d/%d' %(REDIS_HOST,REDIS_PORT,REDIS_DB)
```

**Comment by victorsndvg** [comment]
@vsoch ,

see this file https://github.com/singularityhub/sregistry/blob/master/https/docker-compose.yml, you are not storing the images persistently here.

If think, with the current configuration, if you shutdown your docker-compose running containers (and then remove the containers), and then restart them again (with `docker-compose up -d`) your will lose, at least, users data, tokens, etc. I'm wrong? this is what experienced. Making the DB persistent this does't happen.

About redis, I understand that you are using the redis port only locally, but I think the problem is to expose it outside the container. Definitively is not a good practice. Fix this is as easy as write:
```
redis:
  restart: always
  image: redis:latest
  ports:
- "127.0.0.1:6379:6379"
```

**Comment by vsoch** [comment]
hey @victorsndvg - thanks for the catch on the missing volume, I'll fix that with a quick PR. As for the redis, I don't have the bandwidth right now to investigate and propose the best fix, but a quick look around doesn't show the solution that you are suggesting. In fact I wonder if this would work because the name "redis" is the alias for the (internal) image for docker compose. If you can come up with a PR that has a propose fixed and a clear walk through with showing how it works (outputs, etc.) then we can consider the change. Thanks!y

**Comment by vsoch** [comment]
Here is fix to docker-compose https://github.com/singularityhub/sregistry/pull/75

**Comment by victorsndvg** [comment]
Hi @vsoch , thanks for the fix!

I really don't understand why only expose to localhost the redis port is not a good solution. I've seen it in tens of forum responses. 

This is the sentence that I cannot understand,

>  In fact I wonder if this would work because the name "redis" is the alias for the (internal) image for docker compose. 

Maybe, is it more related with the code itself than with docker management? if this is the case, I think I will not be able to help.  

Can you provide a link explaining the issue or other kind of solutions? Maybe I can go deep with it

**Comment by vsoch** [comment]
hey @victorsndvg ! I finally found a command that shows what I was trying to articulate. The port that redis is using is internal to the docker containers, and is determined by the environment variables for redis. So, if we grep the environment for redis:

```
docker exec sregistry_uwsgi_1 env | grep REDIS
REDIS_PORT=tcp://172.17.0.3:6379
REDIS_PORT_6379_TCP=tcp://172.17.0.3:6379
REDIS_PORT_6379_TCP_ADDR=172.17.0.3
REDIS_PORT_6379_TCP_PORT=6379
REDIS_PORT_6379_TCP_PROTO=tcp
REDIS_NAME=/sregistry_uwsgi_1/redis
REDIS_ENV_GOSU_VERSION=1.10
REDIS_ENV_REDIS_VERSION=4.0.2
REDIS_ENV_REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-4.0.2.tar.gz
REDIS_ENV_REDIS_DOWNLOAD_SHA=b1a0915dbc91b979d06df1977fe594c3fa9b189f1f3d38743a2948c9f7634813
REDIS_1_PORT=tcp://172.17.0.3:6379
REDIS_1_PORT_6379_TCP=tcp://172.17.0.3:6379
REDIS_1_PORT_6379_TCP_ADDR=172.17.0.3
REDIS_1_PORT_6379_TCP_PORT=6379
REDIS_1_PORT_6379_TCP_PROTO=tcp
REDIS_1_NAME=/sregistry_uwsgi_1/redis_1
REDIS_1_ENV_GOSU_VERSION=1.10
REDIS_1_ENV_REDIS_VERSION=4.0.2
REDIS_1_ENV_REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-4.0.2.tar.gz
REDIS_1_ENV_REDIS_DOWNLOAD_SHA=b1a0915dbc91b979d06df1977fe594c3fa9b189f1f3d38743a2948c9f7634813
SREGISTRY_REDIS_1_PORT=tcp://172.17.0.3:6379
SREGISTRY_REDIS_1_PORT_6379_TCP=tcp://172.17.0.3:6379
SREGISTRY_REDIS_1_PORT_6379_TCP_ADDR=172.17.0.3
SREGISTRY_REDIS_1_PORT_6379_TCP_PORT=6379
SREGISTRY_REDIS_1_PORT_6379_TCP_PROTO=tcp
SREGISTRY_REDIS_1_NAME=/sregistry_uwsgi_1/sregistry_redis_1
SREGISTRY_REDIS_1_ENV_GOSU_VERSION=1.10
SREGISTRY_REDIS_1_ENV_REDIS_VERSION=4.0.2
SREGISTRY_REDIS_1_ENV_REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-4.0.2.tar.gz
SREGISTRY_REDIS_1_ENV_REDIS_DOWNLOAD_SHA=b1a0915dbc91b979d06df1977fe594c3fa9b189f1f3d38743a2948c9f7634813
```
the full address starts with 172, and we se it is set here:

```
CELERY_RESULT_BACKEND = 'redis://%s:%d/%d' %(REDIS_HOST,REDIS_PORT,REDIS_DB)
```
and then we can print that variable in python to check:

```
docker exec -it sregistry_uwsgi_1 bash
$ python manage.py shell
fPython 3.5.1 (default, Jun  9 2016, 15:37:54) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shub.settings import *
>>> CELERY_
CELERY_ACCEPT_CONTENT     CELERY_IMPORTS            CELERY_RESULT_BACKEND     CELERY_TASK_SERIALIZER    

>>> CELERY_DEFAULT_QUEUE
'default'
>>> CELERY_RESULT_SERIALIZER
'json'
>>> CELERY_TASK_SERIALIZER
'json'

# note the backend here!
>>> CELERY_RESULT_BACKEND
'redis://172.17.0.3:6379/0'

>>> CELERY_IMPORTS
('shub.apps.api.tasks',)

>>> CELERY_ACCEPT_CONTENT
['json']
```
So what I would try first isn't hard coding a different url (this likely will break the mapping inside because we are using the one above) but try using EXPOSE instead of ports, which I think might fulfull the need to make the port available internally (but not externally). See here: https://stackoverflow.com/questions/35429837/docker-compose-port-mapping

**Comment by victorsndvg** [comment]
Hi @vsoch ,

nice explanation!

This IP's starting with 172.* are those related with the docker virtual network and are relevant for apps and container relationships. When you specify ports with "127.0.0.1:6379:6379" you are telling to docker only to map messages from the local loopback interface to the docker virtual network instead of allowing traffic from the whole internet. Containerized apps are not aware about how messages are filtered before arriving to docker private network.

Once this is said, EXPOSE, as you suggest seems to be the right option for doing that in "docker language". I try both PORTS and EXPOSE option and the difference is seen in iptables.

The following iptables rule disapears while using EXPOSE instead of PORT.
```
... 
Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
...
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.3           tcp dpt:6379
```
All seems to be working properle (not extensively tested).

Thanks for your insights!

I think I can close this issue
