### ISSUE TITLE
Private image access

### ISSUE THREAD

**Issue by vsoch** [singularityhub/sregistry#78]
Private images should default only be pullable by collection owner unless opened up to other users that know the URI.

**Comment by victorsndvg** [comment]
Hi @vsoch ,

sorry, a single question. With the current status (`sregistry/update/private-pull` and `sregistry-cli/add/pull-auth`) who is able to download a container from a private collection?

**Comment by vsoch** [comment]
There is no current status, it needs to be decided and implemented.

**Comment by vsoch** [comment]
This issue is a repeat of #77 , closing here.

**Comment by victorsndvg** [comment]
Yeah @vsoch,

I understand that there is no permissions/security model implemented yet, but I'm able to download a private image using the latests branches (`sregistry/update/private-pull` and `sregistry-cli/add/pull-auth`). With this branches, Why can I pull the images? because I'm the owner? because I know the uri?

If the answer doesn't fit with my needs I've to revert the status of our deployment

Thanks

**Comment by vsoch** [comment]
Oh I can answer that! Right now the check that we do is just that you have a valid token for using a Singularity Registry. Having a token equates to that file on your computer, and specifically it's checked against the credential in the database that is only produced and active for admins and managers. So in summary:

 - a singularity registry user that is an admin or manager (meaning downloading a token for use) is able to pull / push private images. Nobody else is. 

What we've been talking abut is adding levels to that, so for example:

- in addition to being an admin/manager (globally) the pull/push requester must also be the collection owner

What I'm thinking is that an admin should maintain superuser priviledges on all, and then a manager should have pull / push full permissions to collections he/she owns, but then also the ability to assign other users push / pull to those as well. So in the end we would have:

 - admin: superuser, permissions for all
 - manager: can push / pull for collections owned, and assign push / pull to regular users
 - user: just can pull public images, or interact with private that assigned to by manager.

That's what I'm thinking, although I"m not sure about the interface / implementation yet!

**Comment by victorsndvg** [comment]
Hi @vsoch,

although I don't perfectly catch the scope of these permissions, they seem to be what we need. In particular, my first impression when we talked about the roles, I thought the roles where equivalent to this permissions:
- admin = superuser
- manager = admin
- user = none

I think is not needed to reinvent the wheel, there are a lot of "data management tools" with this already done. Some examples are:
- https://github.com/girder/girder
- http://inveniosoftware.org/
- https://zenodo.org/
