### ISSUE TITLE
Client is trying to send a too large body error

### ISSUE THREAD

**Issue by victorsndvg** [singularityhub/sregistry#81]
Hi @vsoch,

I got the following error on the server side:
```
nginx_1   | 2018/01/17 09:11:26 [error] 6#6: *2 client intended to send too large body: 2787366861 bytes, client: 193.144.33.83, server: localhost, request: "POST /api/push/ HTTP/1.1", host: "XXXXXXXXXXX"
```
Can I manage this? I mean to allow sending big images

Thanks!

**Comment by vsoch** [comment]
Could you show me the nginx.conf file? We would want to check this bit:

```
client_max_body_size 8000M;
```
If you've added a block for https it might be missing.

**Comment by victorsndvg** [comment]
You are right,

in the https conf I have
```
client_max_body_size 2000M;
```

Now changed to 8000M and see what happen.

**Comment by victorsndvg** [comment]
solved, Thanks!
