### ISSUE TITLE
Feature request : adding site specific options to rebuild images

### ISSUE THREAD

**Issue by remyd1** [singularityhub/sregistry#91]
Hi,

Like already discussed on Slack, I think it would be nice to have site specific options in `sregistry` options.

Indeed, containers performances are often criticized, not because of the container technology itself, but because people build containers on their own laptop and then bring it without any optimization in the compilation options.

I am talking about specific arch or processor features (SSE, AVX, ...).

To avoid this user behaviour, it should be great to have a system which scan every recipes for `gcc`, `make`, `icc`, `mpicc` command lines and then add these site specific options to the recipe. This can corrupt the container reproducibility, but IMHO, it would be a great option for HPC system administrator.
If we add some `%labels` and `%environment` site specific options, the user would know that the recipe have been modified and how it has been optimize. Moreover, it would happen only on sregistry HPC platforms.

For instance:

```
%environment
    SREGISTRY_GCC_OPTS="-O3 -msse3"

%labels
    sregistry_modified True
    sregistry_gcc_opts -O3,-msse3

%post
    gcc $SREGISTRY_GCC_OPTS ....
```

where `$SREGISTRY_GCC_OPTS` could be added like some sed-like commands (import re / re.compile ... / sub for python).

Best regards,
Rémy

**Comment by vsoch** [comment]
This is a really cool idea! I'm about to get on a long flight so won't be able to respond, but if you would be able to prepare a tiny dummy example (that you would actually want to work) and then walk through the steps for the user and admin, it would help to think about this. id like to make builder plugins for sregistry and this would fit the bill!

**Comment by remyd1** [comment]
Hi @vsoch 

In fact, it is a bit more complicated from what I thought.

Indeed, problems I see with that:
  - Either you have gcc building C(++/fortran) code in the recipe,
  - Or, you already have many makefiles.

For the first option, what I said before can be done, and moreover with some help :
  - https://gist.github.com/thulio/3169653
  - https://software.intel.com/en-us/forums/intel-c-compiler/topic/305798

Otherwise, you have many makefiles; for instance :
  - raxml : https://github.com/stamatak/standard-RAxML
  - hpl linpack : https://ulhpc-tutorials.readthedocs.io/en/latest/advanced/HPL/

You can also have a specific compiler (eg : `icc`), on your cluster which is not avalaible on your laptop, or your version might change (eg `nvcc` with cuda 8 vs cuda 9...).

So IMHO, this rebuilder must be very adaptable (by recipe, and with Nth regexp); with textbox:
```
replacing: "             " by : "             "
```

Eg, for the raxml recipe :
```
 replacing "make -f Makefile.gcc" by : "make -f Makefile.SSE3.MPI.gcc"
```

Then, the `sregistry` must really keep every trace of modification with some convenient labels:

```
%labels
  - SREGISTRY_1_MODIF_STR_FROM "make -f Makefile.gcc"
  - SREGISTRY_1_MODIF_STR_TO "make -f Makefile.SSE3.MPI.gcc"
```

I think `raxml` or `hpl linpack` are good examples.

Best regards,
Rémy

**Comment by vsoch** [comment]
I think before we do this we need to implement a builder plugin, period. Then we can think about customization of it to "rebuild."  Agree?

**Comment by remyd1** [comment]
Yes, :+1:

**Comment by remyd1** [comment]
As I wrote on Slack, I think we might reconsider this issue. Corrupted images is a *bad* idea !

However, having a build farm (using buildbot or whatever) with a lot of desired architecture - IMHO - is our best option, using virtual machines and vagrant.

We could also use [this code](https://github.com/google/cpu_features) to determine the cpu, flags...

It is very easy to use:
```
git clone https://github.com/google/cpu_features.git
cd cpu_features
mkdir build
cd $_
cmake ..
make
./list_cpu_features
```

**Comment by vsoch** [comment]
Could you give an example of how the above would guide building an image?

**Comment by remyd1** [comment]
Hi @vsoch 

I think we could provide a few recommendations on how to optimize the recipes on the desired platform; this could be a list of proposals.

This can be done either in an intrusive way or not. Indeed, we can run the previous code do determine the current cpu flags on a associated node (member of the buildfarm) or the sregistry administrator can import some file, listing the hardware capabilities. Generally all the nodes on a HPC cluster are almost the same.

Or, we can produce many containers (one by host type), with all the possible optimizations, using a buildfarm with vagrant... Maybe we do not need to list all the possibilities but only the most used...

I have no idea what is the way to follow from here. That is just a list of what can be done, and options on how to deal with this request. But IMHO, this must be done in close collaboration with `singularity build`; it could be a part of it.

Ping @gmkurtzer @shahzebsiddiqui @boegel

Rémy.

**Comment by shahzebsiddiqui** [comment]
Hi @remyd1 

I found this link from Intel useful https://software.intel.com/en-us/articles/performance-tools-for-software-developers-intel-compiler-options-for-sse-generation-and-processor-specific-optimizations basically we need to build container for different vectorization since different architecture support different vectorization flags. 

We can tag labels for different vectorization or maybe have something like ``singularity build --vect=[SSE|AVX|AVX2|AVX512] container.simg`` that will attempt to build container with the appropriate vectorization. 

easybuild can do this via optarch but from a Singularity recipe file, user may need to setup their recipe file in a way this can work. This would be useful for apps like FFTW

For gcc there are many options with ``-march=cpu-type`` that can be used see https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html Given there are so many arch it would be very difficult to cover all of the cases, maybe we should first focus on x86 and then figure out if it is feasible that these optimization can be automatically done in singularity or whether user have to do this on the recipe file.

@boegel @gmkurtzer

Shahzeb

**Comment by vsoch** [comment]
hey @remyd1 and @shahzebsiddiqui - The Builders are finished up! They are still separate from the Registry here, but the start to having a command line tool to launch a remote build (that could then go into the registry). Could you please take a look at the documentation:

 - [user documentation](https://singularityhub.github.io/sregistry-cli/client-google-compute)
 - [developer documentation](https://singularityhub.github.io/builders)

and let me know your thoughts - if the use case fits? What we could do is have a builder (on GCP? somewhere else? slurm?) that fits the needs of your use case. It could run separately or then integration to Singularity Registry here. Looking forward to your thoughts! This is fresh off my fingers, so thank you in advance for your patience if I missed anything!

**Comment by vsoch** [comment]
No response to issue, and I'm going to say that customizing builds (when we really just are optimizing storing images, the registry) is currently out of scope. Closing issue.

**Comment by shahzebsiddiqui** [comment]
Hi @vsoch ,

I apologize for not responding to this earlier. The site-specific information was something i had thought about in ``%labels`` section. I have found a mechanism to detect intel architectures based on this link https://software.intel.com/en-us/articles/intel-architecture-and-processor-identification-with-cpuid-model-and-family-numbers

It basically comes down to using ``lscpu`` and checking ``Model:`` number. Also it is safe to take field ``Vendor ID: GenuineIntel`` when differentiating container builds. I was able to confirm this across many intel version, the string ``GenuineIntel`` is found in most architectures.

You can take a full list of cpu flags using ``flags:`` option in lscpu for reporting purpose. As per rebuilding container it is going to be tricky. As per container builds for scientific software, i will primarily use easybuild container integration https://easybuild.readthedocs.io/en/latest/Containers.html to test this out. I have not had time to work on this and i know this was something we discussed with @boegel about building a container repository. Maybe this could be well suited for using Sylabs cloud for publishing containers from easybuild
